'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Shell } from '@/components/shell';
import { Empty, ErrorBox, Eyebrow, Loading, Pill, ReasonDialog } from '@/components/ui';
import { api, fmtDate, fmtMoney } from '@/lib/api';
import { ESCROW, PAYOUT, tone } from '@/lib/labels';
type Hold = { id: string; status: string; amount: string; platformFee: string; releasedAmount: string; refundedAmount: string; beneficiaryOrgId: string; beneficiaryNameAr: string | null; workOrderId: string | null; partOrderId: string | null; autoReleaseAt: string | null; heldAt: string | null; releasedAt: string | null };
type Payout = { id: string; orgId: string; orgNameAr: string | null; amount: string; status: string; scheduledFor: string; processedAt: string | null; failureReason: string | null };
type Payment = { id: string; method: string; status: string; amount: string; payeeOrgId: string; invoiceId: string | null; createdAt: string };
type Approval = { id: string; action: string; entityId: string; payload: { amount?: string; reason_ar?: string }; status: string; requestedBy: string; requestedAt: string; expiresAt: string };
export default function PaymentsPage() {
  const qc = useQueryClient(); const [tab, setTab] = useState<'escrow' | 'payouts' | 'payments'>('escrow'); const [dlg, setDlg] = useState<null | { kind: 'release' | 'freeze' | 'refund'; hold: Hold }>(null);
  const [decideDlg, setDecideDlg] = useState<null | { kind: 'approve' | 'reject'; a: Approval }>(null);
  const holds = useQuery({ queryKey: ['escrow'], queryFn: () => api<Hold[]>('/admin/escrow') }); const payouts = useQuery({ queryKey: ['payouts'], queryFn: () => api<Payout[]>('/admin/payouts') }); const payments = useQuery({ queryKey: ['payments'], queryFn: () => api<Payment[]>('/admin/payments') });
  const approvals = useQuery({ queryKey: ['approvals'], queryFn: () => api<Approval[]>('/admin/approvals?status=requested'), refetchInterval: 30_000 });
  const health = useQuery({ queryKey: ['ledger-health'], queryFn: () => api<{ balanced: boolean; imbalance: string }>('/admin/ledger/health'), refetchInterval: 30_000 });
  const act = useMutation({ mutationFn: ({ kind, id, reason }: { kind: string; id: string; reason: string }) => api(`/admin/escrow/${id}/${kind}`, { method: 'POST', body: JSON.stringify({ reason_ar: reason }) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['escrow'] }); qc.invalidateQueries({ queryKey: ['ledger-health'] }); qc.invalidateQueries({ queryKey: ['approvals'] }); } });
  const decide = useMutation({ mutationFn: ({ kind, id, reason }: { kind: 'approve' | 'reject'; id: string; reason: string }) => api(`/admin/approvals/${id}/${kind}`, { method: 'POST', body: JSON.stringify({ reason_ar: reason }) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['approvals'] }); qc.invalidateQueries({ queryKey: ['escrow'] }); qc.invalidateQueries({ queryKey: ['ledger-health'] }); } });
  const runPayouts = useMutation({ mutationFn: () => api('/admin/payouts/run', { method: 'POST', body: JSON.stringify({}) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['payouts'] }) });
  const execPayout = useMutation({ mutationFn: (id: string) => api(`/admin/payouts/${id}/execute`, { method: 'POST', body: JSON.stringify({}) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['payouts'] }) });
  return <Shell title="الدفعات والضمان" sub="تحرير/تجميد/استرداد بسبب — الاسترداد يتطلب موافقة ثانية (صانع/مدقّق)">
    {(approvals.data?.length ?? 0) > 0 && <div className="card border-warn mb-4 overflow-hidden">
      <div className="p-3 flex items-center gap-2"><Pill label={`${approvals.data!.length}`} tone="pill-warn" /><b>بانتظار الاعتماد — استردادات تحتاج مدقّقاً ثانياً</b><span className="text-xs text-muted">الطالب لا يعتمد طلبه؛ يجوز له سحبه</span></div>
      <table className="tbl"><thead><tr><th>المبلغ</th><th>الحجز</th><th>سبب الطالب</th><th>طُلب</th><th>ينتهي</th><th>قرار</th></tr></thead><tbody>
        {approvals.data!.map((a) => <tr key={a.id}>
          <td className="num font-semibold">{a.payload.amount ? fmtMoney(a.payload.amount) : 'كامل المتبقي'}</td>
          <td className="num text-xs text-muted">{a.entityId.slice(0, 8)}</td>
          <td className="text-sm max-w-[280px] truncate" title={a.payload.reason_ar}>{a.payload.reason_ar ?? '—'}</td>
          <td className="num text-xs text-muted">{fmtDate(a.requestedAt)}</td>
          <td className="num text-xs text-muted">{fmtDate(a.expiresAt)}</td>
          <td className="space-x-1 space-x-reverse"><button className="btn-ghost !h-8" onClick={() => setDecideDlg({ kind: 'approve', a })}>اعتماد</button><button className="btn-ghost !h-8 !text-bad" onClick={() => setDecideDlg({ kind: 'reject', a })}>رفض</button></td>
        </tr>)}
      </tbody></table>
    </div>}
    <div className="grid grid-cols-[1fr_300px] gap-4 mb-4"><div className="flex gap-2 items-center">{([['escrow', 'الضمان (Escrow)'], ['payouts', 'التحويلات'], ['payments', 'الدفعات']] as const).map(([v, l]) => <button key={v} className={`pill ${tab === v ? 'bg-ink text-white' : 'pill-plain'} !px-4 !py-2`} onClick={() => setTab(v)}>{l}</button>)}</div>
      <div className={`card p-3 flex items-center justify-between ${health.data && !health.data.balanced ? 'border-bad' : ''}`}><div><div className="text-xs text-muted">فارق ميزان دفتر الأستاذ</div><div className={`num text-xl font-bold ${health.data?.balanced ? 'text-seal' : 'text-bad'}`}>{health.data?.imbalance ?? '…'}</div></div><Pill label={health.data?.balanced ? 'متوازن' : 'افحص'} tone={health.data?.balanced ? 'pill-seal' : 'pill-bad'} /></div></div>
    {tab === 'escrow' && <>{holds.isLoading && <Loading />}{holds.error && <ErrorBox error={holds.error} retry={() => holds.refetch()} />}{holds.data && (holds.data.length === 0 ? <Empty text="لا توجد مبالغ في الضمان" /> : <div className="card overflow-hidden"><table className="tbl"><thead><tr><th>المستفيد</th><th>المبلغ</th><th>العمولة</th><th>الحالة</th><th>تحرير تلقائي</th><th>المرجع</th><th>إجراء</th></tr></thead><tbody>{holds.data.map((h) => <tr key={h.id}><td className="font-semibold">{h.beneficiaryNameAr ?? h.beneficiaryOrgId.slice(0, 8)}</td><td className="num font-semibold">{fmtMoney(h.amount)}</td><td className="num text-muted">{fmtMoney(h.platformFee)}</td><td><Pill label={ESCROW[h.status] ?? h.status} tone={tone(h.status)} /></td><td className="num text-muted">{fmtDate(h.autoReleaseAt)}</td><td className="num text-xs text-muted">{h.workOrderId ? `WO ${h.workOrderId.slice(0, 8)}` : h.partOrderId ? `PO ${h.partOrderId.slice(0, 8)}` : '—'}</td><td className="space-x-1 space-x-reverse">{(h.status === 'held' || h.status === 'frozen') && <><button className="btn-ghost !h-8" onClick={() => setDlg({ kind: 'release', hold: h })}>تحرير</button>{h.status === 'held' && <button className="btn-ghost !h-8" onClick={() => setDlg({ kind: 'freeze', hold: h })}>تجميد</button>}<button className="btn-ghost !h-8 !text-bad" onClick={() => setDlg({ kind: 'refund', hold: h })}>استرداد</button></>}</td></tr>)}</tbody></table></div>)}</>}
    {tab === 'payouts' && <><div className="flex justify-end mb-3"><button className="btn-ghost" onClick={() => runPayouts.mutate()} disabled={runPayouts.isPending}>تجميع التحويلات المستحقة</button></div>{payouts.isLoading && <Loading />}{payouts.data && (payouts.data.length === 0 ? <Empty text="لا تحويلات بعد" /> : <div className="card overflow-hidden"><table className="tbl"><thead><tr><th>المنشأة</th><th>المبلغ</th><th>الحالة</th><th>مجدول</th><th>نُفِّذ</th><th></th></tr></thead><tbody>{payouts.data.map((p) => <tr key={p.id}><td className="font-semibold">{p.orgNameAr ?? p.orgId.slice(0, 8)}</td><td className="num font-semibold">{fmtMoney(p.amount)}</td><td><Pill label={PAYOUT[p.status] ?? p.status} tone={tone(p.status)} /></td><td className="num text-muted">{fmtDate(p.scheduledFor)}</td><td className="num text-muted">{fmtDate(p.processedAt)}</td><td>{p.status === 'scheduled' && <button className="btn-ghost !h-8" onClick={() => execPayout.mutate(p.id)}>تنفيذ</button>}{p.failureReason && <span className="text-xs text-bad">{p.failureReason}</span>}</td></tr>)}</tbody></table></div>)}</>}
    {tab === 'payments' && <>{payments.isLoading && <Loading />}{payments.data && (payments.data.length === 0 ? <Empty text="لا دفعات بعد" /> : <div className="card overflow-hidden"><table className="tbl"><thead><tr><th>الطريقة</th><th>المبلغ</th><th>الحالة</th><th>الفاتورة</th><th>التاريخ</th></tr></thead><tbody>{payments.data.map((p) => <tr key={p.id}><td>{p.method}</td><td className="num font-semibold">{fmtMoney(p.amount)}</td><td><Pill label={p.status} tone={tone(p.status === 'captured' ? 'paid' : p.status)} /></td><td className="num text-xs text-muted">{p.invoiceId?.slice(0, 8) ?? '—'}</td><td className="num text-muted">{fmtDate(p.createdAt)}</td></tr>)}</tbody></table></div>)}</>}
    {decideDlg && <ReasonDialog
      title={decideDlg.kind === 'approve' ? 'اعتماد الاسترداد — أنت المدقّق الثاني' : 'رفض طلب الاسترداد'}
      hint={decideDlg.kind === 'approve' ? `${decideDlg.a.payload.amount ? fmtMoney(decideDlg.a.payload.amount) : 'كامل المتبقي'} — بموافقتك يخرج المال فعلياً. لا يمكنك اعتماد طلبٍ فتحتَه أنت.` : 'يُغلق الطلب بلا أي حركة مالية؛ يجوز للطالب رفض (سحب) طلبه.'}
      danger={decideDlg.kind === 'approve'} confirmLabel={decideDlg.kind === 'approve' ? 'اعتماد وتنفيذ' : 'رفض'}
      onConfirm={async (reason) => { await decide.mutateAsync({ kind: decideDlg.kind, id: decideDlg.a.id, reason }); }} onClose={() => setDecideDlg(null)} />}
    {dlg && <ReasonDialog title={{ release: 'تحرير المبلغ للمستفيد', freeze: 'تجميد المبلغ (نزاع)', refund: 'استرداد للعميل' }[dlg.kind]} hint={`${fmtMoney(dlg.hold.amount)} · ${dlg.hold.beneficiaryNameAr ?? ''}${dlg.kind === 'refund' ? ' — يتطلب مدقّقاً ثانياً؛ يُسجَّل طلبك باسمك.' : ''}`} danger={dlg.kind !== 'release'} confirmLabel={{ release: 'تحرير', freeze: 'تجميد', refund: 'استرداد' }[dlg.kind]} onConfirm={async (reason) => { await act.mutateAsync({ kind: dlg.kind, id: dlg.hold.id, reason }); }} onClose={() => setDlg(null)} />}
    {act.error && <p className="text-sm text-bad mt-3">{(act.error as Error).message}</p>}
    <div className="mt-6"><Eyebrow>قاعدة</Eyebrow><p className="text-xs text-muted">لا يُعدَّل رصيد مباشرة أبداً — كل تحرير/تجميد/استرداد قيد مزدوج في دفتر الأستاذ مع سبب واسم المنفّذ.</p></div>
  </Shell>;
}
