/** Read-mostly back-office queries (cross-table aggregates are fine here: admin is a reporting context, never a writer of domain state). */
export interface AdminQueryRepository {
  overview(): Promise<{ orgs: { total: number; active: number; pending_kyb: number }; work_orders: { month: number; awaiting_approval: number; in_progress: number; approved_within_1h_pct: number | null }; money: { escrow_held: string; released_30d: string; platform_fees_30d: string; ledger_imbalance: string }; notes: { open: number; overdue: number; outstanding: string }; parts: { open_requests: number; orders_30d: number }; integrations: Array<{ provider: string; last24h: number; succeeded: number; failed: number; dead_letter: number }>; outbox: { pending: number; dead_letter: number } }>;
  audit(q: { action?: string; entity_type?: string; entity_id?: string; org_id?: string; actor_user_id?: string; from?: Date; to?: Date; limit: number; before_id?: bigint }): Promise<Array<{ id: string; occurredAt: Date; actorUserId: string | null; actorType: string; orgId: string | null; action: string; entityType: string; entityId: string | null; before: unknown; after: unknown; requestId: string | null; hash: string; prevHash: string | null }>>;
  settings(): Promise<Array<{ key: string; value: unknown; updatedBy: string | null; updatedAt: Date }>>;
  setSetting(key: string, value: unknown, updatedBy: string): Promise<void>;
  integrationRequests(q: { provider?: string; status?: string; limit: number }): Promise<Array<{ id: string; provider: string; operation: string; idempotencyKey: string; refTable: string | null; refId: string | null; status: string; attempts: number; nextAttemptAt: Date | null; httpStatus: number | null; errorMessage: string | null; latencyMs: number | null; createdAt: Date; updatedAt: Date }>>;
  webhookEvents(q: { provider?: string; limit: number }): Promise<Array<{ id: string; provider: string; eventType: string; externalEventId: string; status: string; receivedAt: Date; processedAt: Date | null; errorMessage: string | null }>>;
  outboxDeadLetters(limit: number): Promise<Array<{ id: string; eventType: string; aggregateType: string; aggregateId: string; attempts: number; lastError: string | null; createdAt: Date }>>;
  payments(q: { status?: string; limit: number }): Promise<Array<{ id: string; method: string; status: string; amount: string; payeeOrgId: string; payerUserId: string | null; invoiceId: string | null; workOrderId: string | null; partOrderId: string | null; createdAt: Date }>>;
  escrowHolds(q: { status?: string; limit: number }): Promise<Array<{ id: string; status: string; amount: string; platformFee: string; releasedAmount: string; refundedAmount: string; beneficiaryOrgId: string; beneficiaryNameAr: string | null; workOrderId: string | null; partOrderId: string | null; autoReleaseAt: Date | null; heldAt: Date | null; releasedAt: Date | null }>>;
  payouts(q: { status?: string; limit: number }): Promise<Array<{ id: string; orgId: string; orgNameAr: string | null; amount: string; status: string; scheduledFor: Date; processedAt: Date | null; failureReason: string | null }>>;
  users(q: { q?: string; platform_role?: string; limit: number }): Promise<Array<{ id: string; phone: string | null; fullNameAr: string | null; status: string; platformRole: string; nafathVerifiedAt: Date | null; createdAt: Date }>>;
  setPlatformRole(userId: string, role: string): Promise<void>;
}
export const ADMIN_QUERY_REPOSITORY = Symbol('ADMIN_QUERY_REPOSITORY');
