import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { PnStatus } from '@sinaaty/shared-types';
import { asTx, PrismaService } from '../../../../prisma';
import type { TxHandle } from '../../../../common/ports/unit-of-work.port';
import type { EnforcementCase, NoteEvent, PromissoryNote, Settlement } from '../../domain/note';
import type { NoteRepository } from '../../domain/repositories';

const d = (v: Prisma.Decimal | null | undefined) => (v == null ? '0.00' : v.toFixed(2)); const D = (v: string) => new Prisma.Decimal(v);
type NoteRow = Prisma.PromissoryNoteGetPayload<Record<string, never>>;
const toNote = (r: NoteRow): PromissoryNote => ({ id: r.id, number: r.number, nafezReference: r.nafezReference, status: r.status, creditorOrgId: r.creditorOrgId, debtorUserId: r.debtorUserId, debtorOrgId: r.debtorOrgId, workOrderId: r.workOrderId, invoiceId: r.invoiceId, partOrderId: r.partOrderId, amount: d(r.amount), outstandingAmount: d(r.outstandingAmount), currency: r.currency, issueDate: r.issueDate, dueDate: r.dueDate, placeOfIssue: r.placeOfIssue, consentSignatureId: r.consentSignatureId, issuanceFee: d(r.issuanceFee), issuedAt: r.issuedAt, closedAt: r.closedAt, cancelledAt: r.cancelledAt, cancelReason: r.cancelReason, createdAt: r.createdAt });
type SetRow = Prisma.SettlementGetPayload<Record<string, never>>;
const toSet = (r: SetRow): Settlement => ({ id: r.id, number: r.number, noteId: r.noteId, invoiceId: r.invoiceId, workOrderId: r.workOrderId, creditorOrgId: r.creditorOrgId, debtorUserId: r.debtorUserId, debtorOrgId: r.debtorOrgId, amountSettled: d(r.amountSettled), contentSha256: r.contentSha256, issuedAt: r.issuedAt });
type EnfRow = Prisma.EnforcementCaseGetPayload<Record<string, never>>;
const toEnf = (r: EnfRow): EnforcementCase => ({ id: r.id, noteId: r.noteId, status: r.status, najizCaseRef: r.najizCaseRef, requestedBy: r.requestedBy, claimedAmount: d(r.claimedAmount), recoveredAmount: d(r.recoveredAmount), isAbandonedVehicle: r.isAbandonedVehicle, storageFeesClaimed: d(r.storageFeesClaimed), timeline: r.timeline, filedAt: r.filedAt, closedAt: r.closedAt, createdAt: r.createdAt });
const OPEN: PnStatus[] = ['issued', 'partially_settled', 'in_enforcement'];

@Injectable()
export class NotePrismaRepository implements NoteRepository {
  constructor(private readonly prisma: PrismaService) {}
  private db(tx?: TxHandle) { return tx ? asTx(tx) : this.prisma; }
  async nextNumber(prefix: 'PN' | 'MK', tx?: TxHandle) { const r = await this.db(tx).$queryRaw<Array<{ n: string }>>`SELECT next_number(${prefix}) AS n`; return r[0]!.n; }
  async create(n: Parameters<NoteRepository['create']>[0], tx?: TxHandle) { const r = await this.db(tx).promissoryNote.create({ data: { number: n.number, status: 'draft', creditorOrgId: n.creditorOrgId, debtorUserId: n.debtorUserId ?? undefined, debtorOrgId: n.debtorOrgId ?? undefined, workOrderId: n.workOrderId ?? undefined, invoiceId: n.invoiceId ?? undefined, partOrderId: n.partOrderId ?? undefined, amount: D(n.amount), outstandingAmount: D(n.amount), dueDate: n.dueDate, placeOfIssue: n.placeOfIssue ?? 'الرياض', consentSignatureId: n.consentSignatureId ?? undefined, issuanceFee: D(n.issuanceFee ?? '0'), createdBy: n.createdBy ?? undefined } }); return toNote(r); }
  async findById(id: string, tx?: TxHandle) { const r = await this.db(tx).promissoryNote.findUnique({ where: { id } }); return r ? toNote(r) : null; }
  async findOpenByWorkOrder(workOrderId: string, tx?: TxHandle) { const r = await this.db(tx).promissoryNote.findFirst({ where: { workOrderId, status: { in: [...OPEN, 'draft', 'pending_consent'] } }, orderBy: { createdAt: 'desc' } }); return r ? toNote(r) : null; }
  async findOpenByPartOrder(partOrderId: string, tx?: TxHandle) { const r = await this.db(tx).promissoryNote.findFirst({ where: { partOrderId, status: { in: [...OPEN, 'draft', 'pending_consent'] } }, orderBy: { createdAt: 'desc' } }); return r ? toNote(r) : null; }
  async findByWorkOrder(workOrderId: string) { const rows = await this.prisma.promissoryNote.findMany({ where: { workOrderId }, orderBy: { createdAt: 'desc' } }); return rows.map(toNote); }
  async list(q: { creditorOrgId?: string; debtorUserId?: string; debtorOrgId?: string; status?: PnStatus[]; overdueOnly?: boolean; limit: number }) { const rows = await this.prisma.promissoryNote.findMany({ where: { creditorOrgId: q.creditorOrgId, debtorUserId: q.debtorUserId, debtorOrgId: q.debtorOrgId, status: q.status ? { in: q.status } : undefined, ...(q.overdueOnly ? { dueDate: { lt: new Date() } } : {}) }, orderBy: { createdAt: 'desc' }, take: q.limit }); return rows.map(toNote); }
  async update(id: string, p: Parameters<NoteRepository['update']>[1], tx?: TxHandle) { await this.db(tx).promissoryNote.update({ where: { id }, data: { status: p.status, nafezReference: p.nafezReference, outstandingAmount: p.outstandingAmount ? D(p.outstandingAmount) : undefined, issueDate: p.issueDate, issuedAt: p.issuedAt, closedAt: p.closedAt, cancelledAt: p.cancelledAt, cancelReason: p.cancelReason, nafezPayload: p.nafezPayload === undefined ? undefined : (p.nafezPayload as Prisma.InputJsonValue), invoiceId: p.invoiceId } }); }
  async addEvent(e: Parameters<NoteRepository['addEvent']>[0], tx?: TxHandle) { await this.db(tx).promissoryNoteEvent.create({ data: { noteId: e.noteId, fromStatus: e.from ?? undefined, toStatus: e.to, amountDelta: e.amountDelta ? D(e.amountDelta) : undefined, paymentId: e.paymentId ?? undefined, providerRef: e.providerRef ?? undefined, providerPayload: e.providerPayload === undefined ? undefined : (e.providerPayload as Prisma.InputJsonValue), actorUserId: e.actorUserId ?? undefined, noteAr: e.noteAr } }); }
  async listEvents(noteId: string): Promise<NoteEvent[]> { const rows = await this.prisma.promissoryNoteEvent.findMany({ where: { noteId }, orderBy: { createdAt: 'asc' } }); return rows.map((r) => ({ id: r.id, fromStatus: r.fromStatus, toStatus: r.toStatus, amountDelta: r.amountDelta ? d(r.amountDelta) : null, paymentId: r.paymentId, providerRef: r.providerRef, noteAr: r.noteAr, createdAt: r.createdAt })); }
  async createSettlement(s: Parameters<NoteRepository['createSettlement']>[0], tx?: TxHandle) { const r = await this.db(tx).settlement.create({ data: { number: s.number, noteId: s.noteId ?? undefined, invoiceId: s.invoiceId ?? undefined, workOrderId: s.workOrderId ?? undefined, creditorOrgId: s.creditorOrgId, debtorUserId: s.debtorUserId ?? undefined, debtorOrgId: s.debtorOrgId ?? undefined, amountSettled: D(s.amountSettled), contentSha256: s.contentSha256 } }); return toSet(r); }
  async findSettlement(id: string) { const r = await this.prisma.settlement.findUnique({ where: { id } }); return r ? toSet(r) : null; }
  async findSettlementByNote(noteId: string) { const r = await this.prisma.settlement.findFirst({ where: { noteId } }); return r ? toSet(r) : null; }
  async addDunning(dn: Parameters<NoteRepository['addDunning']>[0], tx?: TxHandle) { const db = this.db(tx); const exists = await db.dunningNotice.findFirst({ where: { noteId: dn.noteId, step: dn.step }, select: { id: true } }); if (exists) return { inserted: false }; await db.dunningNotice.create({ data: { noteId: dn.noteId, invoiceId: dn.invoiceId ?? undefined, step: dn.step, channel: dn.channel, isFormal: dn.isFormal } }); return { inserted: true }; }
  async listDunning(noteId: string) { const rows = await this.prisma.dunningNotice.findMany({ where: { noteId }, orderBy: { step: 'asc' } }); return rows.map((r) => ({ step: r.step, channel: r.channel, isFormal: r.isFormal, sentAt: r.sentAt })); }
  async createEnforcement(e: Parameters<NoteRepository['createEnforcement']>[0], tx?: TxHandle) { const r = await this.db(tx).enforcementCase.create({ data: { noteId: e.noteId, requestedBy: e.requestedBy, claimedAmount: D(e.claimedAmount), timeline: e.timeline as Prisma.InputJsonValue, isAbandonedVehicle: e.isAbandonedVehicle ?? false, storageFeesClaimed: D(e.storageFeesClaimed ?? '0') } }); return toEnf(r); }
  async findEnforcementByNote(noteId: string) { const r = await this.prisma.enforcementCase.findFirst({ where: { noteId }, orderBy: { createdAt: 'desc' } }); return r ? toEnf(r) : null; }
  async updateEnforcement(id: string, p: Parameters<NoteRepository['updateEnforcement']>[1], tx?: TxHandle) { await this.db(tx).enforcementCase.update({ where: { id }, data: { status: p.status, najizCaseRef: p.najizCaseRef, filedAt: p.filedAt, closedAt: p.closedAt, recoveredAmount: p.recoveredAmount ? D(p.recoveredAmount) : undefined, timeline: p.timeline === undefined ? undefined : (p.timeline as Prisma.InputJsonValue) } }); }
}
