// Generates lib/core/api/generated/endpoints.dart from the OpenAPI document (paths + operationIds).
// Usage: dart run tool/gen_api.dart [path-or-url]   (default: ../../packages/shared-types/openapi.json)
import 'dart:convert';
import 'dart:io';
Future<void> main(List<String> args) async {
  final src = args.isNotEmpty ? args.first : '../../packages/shared-types/openapi.json';
  String text;
  if (src.startsWith('http')) { final c = HttpClient(); final r = await (await c.getUrl(Uri.parse(src))).close(); text = await r.transform(utf8.decoder).join(); c.close(); }
  else { text = await File(src).readAsString(); }
  final doc = jsonDecode(text) as Map<String, dynamic>; final paths = doc['paths'] as Map<String, dynamic>;
  final b = StringBuffer('// GENERATED by tool/gen_api.dart — DO NOT EDIT.\n// ignore_for_file: constant_identifier_names\n\n/// API paths (relative to /v1) and operation ids from the OpenAPI document.\nabstract final class ApiEndpoints {\n');
  final seen = <String>{};
  for (final e in paths.entries) {
    final ops = e.value as Map<String, dynamic>;
    for (final m in ops.entries) {
      final op = m.value as Map<String, dynamic>; final id = (op['operationId'] as String? ?? '${m.key}_${e.key}').replaceAll(RegExp(r'[^A-Za-z0-9]+'), '_');
      var name = id.startsWith('_') ? id.substring(1) : id; while (seen.contains(name)) { name = '${name}_'; } seen.add(name);
      b.writeln("  static const $name = ('${m.key.toUpperCase()}', '${e.key.replaceFirst('/v1', '')}');");
    }
  }
  b.writeln('}\n');
  final out = File('lib/core/api/generated/endpoints.dart'); await out.create(recursive: true); await out.writeAsString(b.toString());
  stdout.writeln('wrote ${out.path} (${seen.length} operations)');
}
