'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Shell } from '@/components/shell';
import { Empty, ErrorBox, Eyebrow, Loading, Pill, ReasonDialog } from '@/components/ui';
import { api, fmtDate } from '@/lib/api';
import { INTEG, NOTE, tone } from '@/lib/labels';
type Integ = { requests: Array<{ id: string; provider: string; operation: string; idempotencyKey: string; status: string; attempts: number; nextAttemptAt: string | null; httpStatus: number | null; errorMessage: string | null; latencyMs: number | null; updatedAt: string }>; webhooks: Array<{ id: string; provider: string; eventType: string; externalEventId: string; status: string; receivedAt: string; errorMessage: string | null }>; dead_letters: Array<{ id: string; eventType: string; aggregateType: string; aggregateId: string; attempts: number; lastError: string | null; createdAt: string }> };
type Note = { id: string; number: string; status: string; amount: string; creditorOrgId: string; dueDate: string; nafezReference: string | null; createdAt: string };
export default function IntegrationsPage() {
  const qc = useQueryClient(); const [retryKey, setRetryKey] = useState<string | null>(null); const [tab, setTab] = useState<'requests' | 'webhooks' | 'dlq' | 'notes'>('dlq');
  const q = useQuery({ queryKey: ['integrations'], queryFn: () => api<Integ>('/admin/integrations'), refetchInterval: 20_000 });
  const notes = useQuery({ queryKey: ['pending-notes'], queryFn: () => api<Note[]>('/admin/promissory-notes?status=draft,pending_consent&limit=100') });
  const retry = useMutation({ mutationFn: ({ key, reason }: { key: string; reason: string }) => api(`/admin/integrations/retry?key=${encodeURIComponent(key)}`, { method: 'POST', body: JSON.stringify({ reason_ar: reason }) }), onSuccess: () => qc.invalidateQueries({ queryKey: ['integrations'] }) });
  const d = q.data;
  return <Shell title="التكاملات" sub="نفاذ · نافذ · PSP · ZATCA — كل طلب له مفتاح تكرار؛ المتوقف يُعاد يدوياً بسبب">
    <div className="flex gap-2 mb-4">{([['dlq', `متوقف (DLQ) ${d?.dead_letters.length ?? ''}`], ['requests', 'طلبات التكامل'], ['webhooks', 'Webhooks'], ['notes', `سندات معلّقة ${notes.data?.length ?? ''}`]] as const).map(([v, l]) => <button key={v} className={`pill ${tab === v ? 'bg-ink text-white' : 'pill-plain'} !px-4 !py-2`} onClick={() => setTab(v)}>{l}</button>)}</div>
    {q.isLoading && <Loading />}{q.error && <ErrorBox error={q.error} retry={() => q.refetch()} />}
    {d && tab === 'dlq' && (d.dead_letters.length === 0 ? <Empty text="لا توجد أحداث متوقفة — كل المعالجات تعمل" /> : <div className="card overflow-hidden"><table className="tbl"><thead><tr><th>الحدث</th><th>الكيان</th><th>محاولات</th><th>آخر خطأ</th><th>منذ</th><th></th></tr></thead><tbody>{d.dead_letters.map((x) => <tr key={x.id}><td className="font-semibold">{x.eventType}</td><td className="num text-xs text-muted">{x.aggregateType} · {x.aggregateId.slice(0, 8)}</td><td className="num">{x.attempts}</td><td className="text-xs text-bad max-w-[380px] truncate" title={x.lastError ?? ''}>{x.lastError}</td><td className="num text-muted">{fmtDate(x.createdAt)}</td><td><button className="btn-ghost !h-8" onClick={() => setRetryKey(x.id)}>إعادة المحاولة</button></td></tr>)}</tbody></table></div>)}
    {d && tab === 'requests' && <div className="card overflow-hidden"><table className="tbl"><thead><tr><th>المزوّد</th><th>العملية</th><th>الحالة</th><th>محاولات</th><th>HTTP</th><th>زمن</th><th>آخر تحديث</th><th></th></tr></thead><tbody>{d.requests.map((r) => <tr key={r.id}><td className="font-semibold">{r.provider}</td><td className="text-xs">{r.operation}</td><td><Pill label={INTEG[r.status] ?? r.status} tone={tone(r.status)} /></td><td className="num">{r.attempts}</td><td className="num">{r.httpStatus ?? '—'}</td><td className="num">{r.latencyMs != null ? `${r.latencyMs}ms` : '—'}</td><td className="num text-muted">{fmtDate(r.updatedAt)}</td><td>{(r.status === 'failed' || r.status === 'dead_letter') && r.idempotencyKey.startsWith('outbox:') && <button className="btn-ghost !h-8" onClick={() => setRetryKey(r.idempotencyKey)}>إعادة</button>}</td></tr>)}</tbody></table></div>}
    {d && tab === 'webhooks' && <div className="card overflow-hidden"><table className="tbl"><thead><tr><th>المزوّد</th><th>الحدث</th><th>المعرّف الخارجي</th><th>الحالة</th><th>استُلم</th><th>خطأ</th></tr></thead><tbody>{d.webhooks.map((w) => <tr key={w.id}><td className="font-semibold">{w.provider}</td><td className="text-xs">{w.eventType}</td><td className="num text-xs">{w.externalEventId}</td><td><Pill label={w.status === 'processed' ? 'معالَج' : w.status === 'failed' ? 'فشل' : 'مستلم'} tone={tone(w.status)} /></td><td className="num text-muted">{fmtDate(w.receivedAt)}</td><td className="text-xs text-bad">{w.errorMessage}</td></tr>)}</tbody></table></div>}
    {tab === 'notes' && <div className="space-y-3"><Eyebrow>سندات لم تُصدر بعد في نافذ (مسودة / بانتظار الموافقة)</Eyebrow>{notes.data?.length === 0 ? <Empty text="لا سندات معلّقة — كل السندات صادرة" /> : <div className="card overflow-hidden"><table className="tbl"><thead><tr><th>السند</th><th>الحالة</th><th>المبلغ</th><th>مرجع نافذ</th><th>أُنشئ</th></tr></thead><tbody>{(notes.data ?? []).map((n) => <tr key={n.id}><td className="num font-semibold">{n.number}</td><td><Pill label={NOTE[n.status] ?? n.status} tone={tone(n.status)} /></td><td className="num">{n.amount}</td><td className="num text-xs">{n.nafezReference ?? '—'}</td><td className="num text-muted">{fmtDate(n.createdAt)}</td></tr>)}</tbody></table></div>}</div>}
    {retryKey && <ReasonDialog title="إعادة محاولة التكامل" hint={retryKey} confirmLabel="إعادة المحاولة الآن" onConfirm={async (reason) => { await retry.mutateAsync({ key: retryKey, reason }); }} onClose={() => setRetryKey(null)} />}
  </Shell>;
}
