import type { EnforcementStatus, PnStatus } from '@sinaaty/shared-types';
export interface PromissoryNote { id: string; number: string; nafezReference: string | null; status: PnStatus; creditorOrgId: string; debtorUserId: string | null; debtorOrgId: string | null; workOrderId: string | null; invoiceId: string | null; partOrderId: string | null; amount: string; outstandingAmount: string; currency: string; issueDate: Date | null; dueDate: Date; placeOfIssue: string; consentSignatureId: string | null; issuanceFee: string; issuedAt: Date | null; closedAt: Date | null; cancelledAt: Date | null; cancelReason: string | null; createdAt: Date }
export interface NoteEvent { id: string; fromStatus: PnStatus | null; toStatus: PnStatus; amountDelta: string | null; paymentId: string | null; providerRef: string | null; noteAr: string | null; createdAt: Date }
export interface Settlement { id: string; number: string; noteId: string | null; invoiceId: string | null; workOrderId: string | null; creditorOrgId: string; debtorUserId: string | null; debtorOrgId: string | null; amountSettled: string; contentSha256: string; issuedAt: Date }
export interface EnforcementCase { id: string; noteId: string; status: EnforcementStatus; najizCaseRef: string | null; requestedBy: string | null; claimedAmount: string; recoveredAmount: string; isAbandonedVehicle: boolean; storageFeesClaimed: string; timeline: unknown; filedAt: Date | null; closedAt: Date | null; createdAt: Date }
export const PN_TRANSITIONS: Record<PnStatus, PnStatus[]> = { draft: ['pending_consent', 'issued', 'cancelled', 'rejected'], pending_consent: ['issued', 'rejected', 'cancelled'], issued: ['partially_settled', 'closed', 'cancelled', 'in_enforcement'], partially_settled: ['partially_settled', 'closed', 'in_enforcement'], in_enforcement: ['enforced', 'closed', 'partially_settled'], enforced: ['closed'], closed: [], cancelled: [], rejected: [] };
export const canTransitionNote = (from: PnStatus, to: PnStatus) => PN_TRANSITIONS[from].includes(to);
export const OPEN_STATUSES: PnStatus[] = ['issued', 'partially_settled', 'in_enforcement'];
export const isOverdue = (n: Pick<PromissoryNote, 'dueDate' | 'status'>, now: Date) => OPEN_STATUSES.includes(n.status) && n.dueDate.getTime() < now.getTime();
/** Dunning step due dates: schedule (days after due) → step index (1-based). */
export function dunningStepsDue(dueDate: Date, scheduleDays: number[], now: Date): number[] { const out: number[] = []; scheduleDays.forEach((d, i) => { if (now.getTime() >= dueDate.getTime() + d * 86_400_000) out.push(i + 1); }); return out; }
