import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { BidStatus } from '@sinaaty/shared-types';
import { asTx, PrismaService } from '../../../../prisma';
import type { TxHandle } from '../../../../common/ports/unit-of-work.port';
import type { CatalogPart, Fitment, InventoryItem, PartBid, PartOrder, PartOrderItem, PartRequest, PartSerial, TradeAccount, Warranty } from '../../domain/parts';
import { SUPPLIER_ORG_TYPES } from '../../domain/parts';
import type { PartsRepository } from '../../domain/repositories';

const d = (v: Prisma.Decimal | null | undefined) => (v == null ? null : v.toFixed(2)); const d0 = (v: Prisma.Decimal | null | undefined) => d(v) ?? '0.00'; const D = (v: string) => new Prisma.Decimal(v);
type CatRow = Prisma.PartsCatalogGetPayload<{ include: { brand: true } }>;
const toCat = (r: CatRow): CatalogPart => ({ id: r.id, brandId: r.brandId, brandNameAr: r.brand.nameAr, partNumber: r.partNumber, oemNumbers: r.oemNumbers, categoryId: r.categoryId, nameAr: r.nameAr, nameEn: r.nameEn, isSerialized: r.isSerialized, createdByOrgId: r.createdByOrgId });
const toFit = (r: Prisma.PartFitmentGetPayload<Record<string, never>>): Fitment => ({ id: r.id, catalogId: r.catalogId, makeId: r.makeId, modelId: r.modelId, yearFrom: r.yearFrom, yearTo: r.yearTo, engineCode: r.engineCode });
const toInv = (r: Prisma.SupplierInventoryGetPayload<Record<string, never>>): InventoryItem => ({ id: r.id, orgId: r.orgId, catalogId: r.catalogId, categoryId: r.categoryId, makeId: r.makeId, modelId: r.modelId, yearFrom: r.yearFrom, yearTo: r.yearTo, partNumber: r.partNumber, condition: r.condition, titleAr: r.titleAr, price: d(r.price), tradePrice: d(r.tradePrice), quantity: r.quantity, reservedQty: r.reservedQty, donorVin: r.donorVin, warrantyDays: r.warrantyDays, leadTimeHours: r.leadTimeHours, externalSku: r.externalSku, isActive: r.isActive });
const toReq = (r: Prisma.PartRequestGetPayload<Record<string, never>>): PartRequest => ({ id: r.id, number: r.number, requesterUserId: r.requesterUserId, requesterOrgId: r.requesterOrgId, workOrderId: r.workOrderId, vehicleId: r.vehicleId, vin: r.vin, categoryId: r.categoryId, partNameAr: r.partNameAr, partNumber: r.partNumber, descriptionAr: r.descriptionAr, acceptedConditions: r.acceptedConditions, quantity: r.quantity, searchRadiusKm: r.searchRadiusKm, biddingEndsAt: r.biddingEndsAt, status: r.status, awardedBidId: r.awardedBidId, createdAt: r.createdAt });
const toBid = (r: Prisma.PartBidGetPayload<Record<string, never>>): PartBid => ({ id: r.id, requestId: r.requestId, supplierOrgId: r.supplierOrgId, inventoryId: r.inventoryId, condition: r.condition, unitPrice: d0(r.unitPrice), quantity: r.quantity, vatRate: r.vatRate.toFixed(2), deliveryFee: d0(r.deliveryFee), deliveryEtaHours: r.deliveryEtaHours, warrantyDays: r.warrantyDays, warrantyTermsAr: r.warrantyTermsAr, donorVin: r.donorVin, notesAr: r.notesAr, status: r.status, createdAt: r.createdAt, updatedAt: r.updatedAt });
type OrderRow = Prisma.PartOrderGetPayload<{ include: { partOrderItems: true } }>;
const toItem = (i: Prisma.PartOrderItemGetPayload<Record<string, never>>): PartOrderItem => ({ id: i.id, inventoryId: i.inventoryId, catalogId: i.catalogId, descriptionAr: i.descriptionAr, condition: i.condition, quantity: i.quantity, unitPrice: d0(i.unitPrice), vatRate: i.vatRate.toFixed(2), lineTotal: d0(i.lineTotal), warrantyDays: i.warrantyDays });
const toOrder = (r: OrderRow): PartOrder => ({ id: r.id, number: r.number, source: r.source, requestId: r.requestId, bidId: r.bidId, tradeAccountId: r.tradeAccountId, buyerUserId: r.buyerUserId, buyerOrgId: r.buyerOrgId, supplierOrgId: r.supplierOrgId, workOrderId: r.workOrderId, transportJobId: r.transportJobId, paymentTerms: r.paymentTerms, status: r.status, subtotal: d0(r.subtotal), deliveryFee: d0(r.deliveryFee), vatAmount: d0(r.vatAmount), total: d0(r.total), shippedAt: r.shippedAt, deliveredAt: r.deliveredAt, installedAt: r.installedAt, confirmedAt: r.confirmedAt, autoConfirmAt: r.autoConfirmAt, createdAt: r.createdAt, items: r.partOrderItems.map(toItem) });
const toTa = (r: Prisma.TradeAccountGetPayload<Record<string, never>>): TradeAccount => ({ id: r.id, sellerOrgId: r.sellerOrgId, buyerOrgId: r.buyerOrgId, status: r.status, creditLimit: d0(r.creditLimit), outstanding: d0(r.outstanding), paymentTermsDays: r.paymentTermsDays, discountBps: r.discountBps, requiresNote: r.requiresNote, approvedBy: r.approvedBy, approvedAt: r.approvedAt, createdAt: r.createdAt });
const toSer = (r: Prisma.PartSerialGetPayload<Record<string, never>>): PartSerial => ({ id: r.id, catalogId: r.catalogId, serialNumber: r.serialNumber, qrToken: r.qrToken, batchCode: r.batchCode, issuerOrgId: r.issuerOrgId, ownerOrgId: r.ownerOrgId, status: r.status, partOrderId: r.partOrderId, workOrderItemId: r.workOrderItemId, vehicleId: r.vehicleId, installedAt: r.installedAt, scanCount: r.scanCount, lastScannedAt: r.lastScannedAt });
const toWar = (r: Prisma.WarrantyGetPayload<Record<string, never>>): Warranty => ({ id: r.id, number: r.number, qrToken: r.qrToken, issuerOrgId: r.issuerOrgId, beneficiaryUserId: r.beneficiaryUserId, beneficiaryOrgId: r.beneficiaryOrgId, vehicleId: r.vehicleId, partOrderId: r.partOrderId, workOrderItemId: r.workOrderItemId, partSerialId: r.partSerialId, installerOrgId: r.installerOrgId, covers: r.covers, condition: r.condition, coverageAr: r.coverageAr, startsAt: r.startsAt, endsAt: r.endsAt, status: r.status, contentSha256: r.contentSha256 });

@Injectable()
export class PartsPrismaRepository implements PartsRepository {
  constructor(private readonly prisma: PrismaService) {}
  private db(tx?: TxHandle) { return tx ? asTx(tx) : this.prisma; }
  async nextNumber(prefix: 'PR' | 'PO' | 'WR' | 'GB', tx?: TxHandle) { const r = await this.db(tx).$queryRaw<Array<{ n: string }>>`SELECT next_number(${prefix}) AS n`; return r[0]!.n; }
  // ---- catalog
  async listBrands() { return this.prisma.partBrand.findMany({ orderBy: { nameEn: 'asc' }, select: { id: true, nameAr: true, nameEn: true, isOem: true, agentOrgId: true } }); }
  async findBrandByName(nameEn: string) { return this.prisma.partBrand.findFirst({ where: { nameEn: { equals: nameEn, mode: 'insensitive' } }, select: { id: true } }); }
  async createBrand(b: { nameAr: string; nameEn: string; isOem: boolean; agentOrgId?: string | null }) { return this.prisma.partBrand.create({ data: { nameAr: b.nameAr, nameEn: b.nameEn, isOem: b.isOem, agentOrgId: b.agentOrgId ?? undefined }, select: { id: true } }); }
  async findCategoryByCode(code: string) { return this.prisma.partCategory.findUnique({ where: { code }, select: { id: true } }); }
  async upsertCatalog(p: Parameters<PartsRepository['upsertCatalog']>[0], tx?: TxHandle) { const r = await this.db(tx).partsCatalog.upsert({ where: { brandId_partNumber: { brandId: p.brandId, partNumber: p.partNumber } }, update: { nameAr: p.nameAr, nameEn: p.nameEn ?? undefined, oemNumbers: p.oemNumbers ?? undefined, categoryId: p.categoryId ?? undefined, isSerialized: p.isSerialized ?? undefined }, create: { brandId: p.brandId, partNumber: p.partNumber, nameAr: p.nameAr, nameEn: p.nameEn ?? undefined, oemNumbers: p.oemNumbers ?? [], categoryId: p.categoryId ?? undefined, isSerialized: p.isSerialized ?? false, createdByOrgId: p.createdByOrgId ?? undefined }, include: { brand: true } }); return toCat(r); }
  async findCatalog(id: string) { const r = await this.prisma.partsCatalog.findUnique({ where: { id }, include: { brand: true } }); return r ? toCat(r) : null; }
  async searchCatalog(q: { text?: string; partNumber?: string; limit: number }) { const rows = await this.prisma.partsCatalog.findMany({ where: { AND: [q.partNumber ? { OR: [{ partNumber: { contains: q.partNumber, mode: 'insensitive' } }, { oemNumbers: { has: q.partNumber } }] } : {}, q.text ? { OR: [{ nameAr: { contains: q.text } }, { nameEn: { contains: q.text, mode: 'insensitive' } }] } : {}] }, take: q.limit, include: { brand: true }, orderBy: { updatedAt: 'desc' } }); return rows.map(toCat); }
  async upsertFitment(f: Parameters<PartsRepository['upsertFitment']>[0], tx?: TxHandle) {
    const db = this.db(tx); const existing = await db.partFitment.findFirst({ where: { catalogId: f.catalogId, makeId: f.makeId, modelId: f.modelId ?? null, yearFrom: f.yearFrom ?? null, yearTo: f.yearTo ?? null, engineCode: f.engineCode ?? null } });
    if (existing) return toFit(existing);
    return toFit(await db.partFitment.create({ data: { catalogId: f.catalogId, makeId: f.makeId, modelId: f.modelId ?? undefined, yearFrom: f.yearFrom ?? undefined, yearTo: f.yearTo ?? undefined, engineCode: f.engineCode ?? undefined, source: f.source ?? 'agent' } }));
  }
  async fitmentsFor(v: { makeId: number; modelId: number | null; year: number | null }) { const rows = await this.prisma.partFitment.findMany({ where: { makeId: v.makeId, OR: [{ modelId: null }, ...(v.modelId ? [{ modelId: v.modelId }] : [])], ...(v.year ? { AND: [{ OR: [{ yearFrom: null }, { yearFrom: { lte: v.year } }] }, { OR: [{ yearTo: null }, { yearTo: { gte: v.year } }] }] } : {}) }, take: 500 }); return rows.map(toFit); }
  async ensureMakeModel(makeEn: string, makeAr: string | undefined, modelEn?: string) { const make = await this.prisma.vehicleMake.upsert({ where: { nameEn: makeEn }, update: {}, create: { nameEn: makeEn, nameAr: makeAr ?? makeEn } }); if (!modelEn) return { makeId: make.id, modelId: null }; const model = await this.prisma.vehicleModel.upsert({ where: { makeId_nameEn: { makeId: make.id, nameEn: modelEn } }, update: {}, create: { makeId: make.id, nameEn: modelEn, nameAr: modelEn } }); return { makeId: make.id, modelId: model.id }; }
  // ---- inventory
  async upsertInventory(i: Parameters<PartsRepository['upsertInventory']>[0], tx?: TxHandle) {
    const db = this.db(tx); const data = { catalogId: i.catalogId ?? undefined, categoryId: i.categoryId ?? undefined, makeId: i.makeId ?? undefined, modelId: i.modelId ?? undefined, yearFrom: i.yearFrom ?? undefined, yearTo: i.yearTo ?? undefined, partNumber: i.partNumber ?? undefined, condition: i.condition, titleAr: i.titleAr, price: i.price ? D(i.price) : undefined, tradePrice: i.tradePrice ? D(i.tradePrice) : undefined, quantity: i.quantity, donorVin: i.donorVin ?? undefined, warrantyDays: i.warrantyDays ?? 0, leadTimeHours: i.leadTimeHours ?? undefined, syncedAt: i.syncedAt ?? undefined, isActive: true };
    if (i.externalSku) { const ex = await db.supplierInventory.findFirst({ where: { orgId: i.orgId, externalSku: i.externalSku } }); if (ex) return toInv(await db.supplierInventory.update({ where: { id: ex.id }, data })); }
    return toInv(await db.supplierInventory.create({ data: { orgId: i.orgId, externalSku: i.externalSku ?? undefined, ...data } }));
  }
  async findInventory(id: string, tx?: TxHandle) { const r = await this.db(tx).supplierInventory.findUnique({ where: { id } }); return r ? toInv(r) : null; }
  async listInventory(q: Parameters<PartsRepository['listInventory']>[0]) { const rows = await this.prisma.supplierInventory.findMany({ where: { orgId: q.orgId, catalogId: q.catalogIds ? { in: q.catalogIds } : undefined, makeId: q.makeId, modelId: q.modelId === undefined ? undefined : q.modelId, categoryId: q.categoryId, ...(q.activeOnly ? { isActive: true, quantity: { gt: 0 } } : {}) }, take: q.limit, orderBy: { updatedAt: 'desc' } }); return rows.map(toInv); }
  async adjustInventory(id: string, delta: { quantity?: number; reserved?: number }, tx?: TxHandle) { await this.db(tx).supplierInventory.update({ where: { id }, data: { quantity: delta.quantity ? { increment: delta.quantity } : undefined, reservedQty: delta.reserved ? { increment: delta.reserved } : undefined } }); }
  async createSyncRun(r: Parameters<PartsRepository['createSyncRun']>[0]) { return this.prisma.inventorySyncRun.create({ data: { orgId: r.orgId, source: r.source, rowsTotal: r.rowsTotal, rowsUpserted: r.rowsUpserted, rowsFailed: r.rowsFailed, errors: r.errors as Prisma.InputJsonValue, finishedAt: new Date() }, select: { id: true } }); }
  // ---- requests
  async createRequest(r: Parameters<PartsRepository['createRequest']>[0], tx?: TxHandle) {
    const db = this.db(tx);
    const row = await db.partRequest.create({ data: { number: r.number, requesterUserId: r.requesterUserId ?? undefined, requesterOrgId: r.requesterOrgId ?? undefined, workOrderId: r.workOrderId ?? undefined, vehicleId: r.vehicleId ?? undefined, vin: r.vin ?? undefined, categoryId: r.categoryId ?? undefined, partNameAr: r.partNameAr, partNumber: r.partNumber ?? undefined, descriptionAr: r.descriptionAr ?? undefined, acceptedConditions: r.acceptedConditions, quantity: r.quantity, searchRadiusKm: r.searchRadiusKm, biddingEndsAt: r.biddingEndsAt } });
    if (r.deliverTo) await db.$executeRaw`UPDATE part_requests SET deliver_to_geo = ST_SetSRID(ST_MakePoint(${r.deliverTo.lng}, ${r.deliverTo.lat}), 4326)::geography WHERE id = ${row.id}::uuid`;
    return toReq(row);
  }
  async findRequest(id: string, tx?: TxHandle) { const r = await this.db(tx).partRequest.findUnique({ where: { id } }); return r ? toReq(r) : null; }
  async listRequests(q: Parameters<PartsRepository['listRequests']>[0]) { const rows = await this.prisma.partRequest.findMany({ where: { requesterUserId: q.requesterUserId, requesterOrgId: q.requesterOrgId, status: q.status ? { in: q.status } : undefined, biddingEndsAt: q.endedBefore ? { lte: q.endedBefore } : undefined, ...(q.recipientOrgId ? { partRequestRecipients: { some: { orgId: q.recipientOrgId } } } : {}) }, orderBy: { createdAt: 'desc' }, take: q.limit }); return rows.map(toReq); }
  async updateRequest(id: string, p: Parameters<PartsRepository['updateRequest']>[1], tx?: TxHandle) { await this.db(tx).partRequest.update({ where: { id }, data: { status: p.status, awardedBidId: p.awardedBidId === undefined ? undefined : p.awardedBidId } }); }
  async deliveryPointOf(orderId: string) {
    const rows = await this.prisma.$queryRaw<Array<{ lat: number | null; lng: number | null; address: string | null }>>`
      SELECT COALESCE(ST_Y(r.deliver_to_geo::geometry), ST_Y(bl.geo::geometry)) AS lat,
             COALESCE(ST_X(r.deliver_to_geo::geometry), ST_X(bl.geo::geometry)) AS lng,
             COALESCE(r.deliver_to_address, bl.city) AS address
      FROM part_orders o
      LEFT JOIN part_requests r ON r.id = o.request_id
      LEFT JOIN organization_locations bl ON bl.org_id = o.buyer_org_id AND bl.is_primary = true
      WHERE o.id = ${orderId}::uuid`;
    const r = rows[0];
    return r?.lat == null || r?.lng == null ? null : { lat: Number(r.lat), lng: Number(r.lng), address: r.address };
  }
  async whereOfOrgs(orgIds: string[], from?: { lat: number; lng: number } | { requestId: string }) {
    const out = new Map<string, { city: string | null; district: string | null; distanceKm: number | null }>();
    if (!orgIds.length) return out;
    const point = from && 'requestId' in from
      ? Prisma.sql`(SELECT deliver_to_geo FROM part_requests WHERE id = ${from.requestId}::uuid)`
      : from ? Prisma.sql`ST_SetSRID(ST_MakePoint(${from.lng}, ${from.lat}), 4326)::geography` : null;
    const rows = await this.prisma.$queryRaw<Array<{ org_id: string; city: string | null; district: string | null; distance_km: number | null }>>`
      SELECT l.org_id, l.city, l.district,
             ${point ? Prisma.sql`(ST_Distance(l.geo, ${point}) / 1000.0)::float` : Prisma.sql`NULL::float`} AS distance_km
      FROM organization_locations l
      WHERE l.is_primary = true AND l.org_id = ANY(${orgIds}::uuid[])`;
    for (const r of rows) out.set(r.org_id, { city: r.city, district: r.district, distanceKm: r.distance_km == null ? null : Math.round(r.distance_km * 10) / 10 });
    return out;
  }
  async matchSuppliers(requestId: string, radiusKm: number, limit: number) {
    const rows = await this.prisma.$queryRaw<Array<{ org_id: string; distance_km: number | null }>>`
      SELECT o.id AS org_id, MIN(CASE WHEN r.deliver_to_geo IS NULL OR l.geo IS NULL THEN NULL ELSE ST_Distance(l.geo, r.deliver_to_geo) / 1000.0 END)::float AS distance_km
      FROM part_requests r CROSS JOIN organizations o LEFT JOIN organization_locations l ON l.org_id = o.id
      WHERE r.id = ${requestId}::uuid AND o.status = 'active' AND o.type::text = ANY(${[...SUPPLIER_ORG_TYPES]}::text[])
        AND (r.deliver_to_geo IS NULL OR l.geo IS NULL OR ST_DWithin(l.geo, r.deliver_to_geo, ${radiusKm * 1000}))
      GROUP BY o.id ORDER BY distance_km NULLS LAST LIMIT ${limit}`;
    return rows.map((r) => ({ orgId: r.org_id, distanceKm: r.distance_km == null ? null : Math.round(r.distance_km * 100) / 100 }));
  }
  async addRecipients(requestId: string, rows: Array<{ orgId: string; distanceKm: number | null }>, tx?: TxHandle) { if (!rows.length) return 0; const r = await this.db(tx).partRequestRecipient.createMany({ data: rows.map((x) => ({ requestId, orgId: x.orgId, distanceKm: x.distanceKm == null ? undefined : new Prisma.Decimal(x.distanceKm) })), skipDuplicates: true }); return r.count; }
  async listRecipients(requestId: string) { const rows = await this.prisma.partRequestRecipient.findMany({ where: { requestId } }); return rows.map((r) => ({ orgId: r.orgId, distanceKm: r.distanceKm == null ? null : Number(r.distanceKm), notifiedAt: r.notifiedAt, viewedAt: r.viewedAt })); }
  async upsertBid(b: Parameters<PartsRepository['upsertBid']>[0], tx?: TxHandle) { const data = { inventoryId: b.inventoryId ?? undefined, condition: b.condition, unitPrice: D(b.unitPrice), quantity: b.quantity, vatRate: D(b.vatRate), deliveryFee: D(b.deliveryFee), deliveryEtaHours: b.deliveryEtaHours ?? undefined, warrantyDays: b.warrantyDays, warrantyTermsAr: b.warrantyTermsAr ?? undefined, donorVin: b.donorVin ?? undefined, notesAr: b.notesAr ?? undefined, status: 'submitted' as const }; const r = await this.db(tx).partBid.upsert({ where: { requestId_supplierOrgId: { requestId: b.requestId, supplierOrgId: b.supplierOrgId } }, update: data, create: { requestId: b.requestId, supplierOrgId: b.supplierOrgId, ...data } }); return toBid(r); }
  async findBid(id: string, tx?: TxHandle) { const r = await this.db(tx).partBid.findUnique({ where: { id } }); return r ? toBid(r) : null; }
  async listBids(requestId: string) { const rows = await this.prisma.partBid.findMany({ where: { requestId }, orderBy: [{ unitPrice: 'asc' }, { createdAt: 'asc' }] }); return rows.map(toBid); }
  async setBidStatus(id: string, status: BidStatus, tx?: TxHandle) { await this.db(tx).partBid.update({ where: { id }, data: { status } }); }
  async setBidsStatus(requestId: string, from: BidStatus[], to: BidStatus, exceptId?: string, tx?: TxHandle) { const r = await this.db(tx).partBid.updateMany({ where: { requestId, status: { in: from }, id: exceptId ? { not: exceptId } : undefined }, data: { status: to } }); return r.count; }
  // ---- orders
  async createOrder(o: Parameters<PartsRepository['createOrder']>[0], tx?: TxHandle) { const r = await this.db(tx).partOrder.create({ data: { number: o.number, source: o.source, requestId: o.requestId ?? undefined, bidId: o.bidId ?? undefined, tradeAccountId: o.tradeAccountId ?? undefined, buyerUserId: o.buyerUserId ?? undefined, buyerOrgId: o.buyerOrgId ?? undefined, supplierOrgId: o.supplierOrgId, workOrderId: o.workOrderId ?? undefined, paymentTerms: o.paymentTerms, status: o.status, subtotal: D(o.subtotal), deliveryFee: D(o.deliveryFee), vatAmount: D(o.vatAmount), total: D(o.total), autoConfirmAt: o.autoConfirmAt ?? undefined, partOrderItems: { create: o.items.map((i) => ({ inventoryId: i.inventoryId ?? undefined, catalogId: i.catalogId ?? undefined, descriptionAr: i.descriptionAr, condition: i.condition, quantity: i.quantity, unitPrice: D(i.unitPrice), vatRate: D(i.vatRate), lineTotal: D(i.lineTotal), warrantyDays: i.warrantyDays })) } }, include: { partOrderItems: true } }); return toOrder(r); }
  async findOrder(id: string, tx?: TxHandle) { const r = await this.db(tx).partOrder.findUnique({ where: { id }, include: { partOrderItems: true } }); return r ? toOrder(r) : null; }
  async findOrderByInvoice(invoiceId: string) { const inv = await this.prisma.invoice.findUnique({ where: { id: invoiceId }, select: { partOrderId: true } }); if (!inv?.partOrderId) return null; return this.findOrder(inv.partOrderId); }
  async listOrders(q: Parameters<PartsRepository['listOrders']>[0]) { const rows = await this.prisma.partOrder.findMany({ where: { buyerUserId: q.buyerUserId, buyerOrgId: q.buyerOrgId, supplierOrgId: q.supplierOrgId, tradeAccountId: q.tradeAccountId, status: q.status ? { in: q.status } : undefined, autoConfirmAt: q.autoConfirmBefore ? { lte: q.autoConfirmBefore } : undefined }, include: { partOrderItems: true }, orderBy: { createdAt: 'desc' }, take: q.limit }); return rows.map(toOrder); }
  async updateOrder(id: string, p: Parameters<PartsRepository['updateOrder']>[1], tx?: TxHandle) { await this.db(tx).partOrder.update({ where: { id }, data: { status: p.status, shippedAt: p.shippedAt, deliveredAt: p.deliveredAt, installedAt: p.installedAt, confirmedAt: p.confirmedAt, autoConfirmAt: p.autoConfirmAt, cancelledAt: p.cancelledAt, transportJobId: p.transportJobId } }); }
  async linkInvoice(orderId: string, invoiceId: string, tx?: TxHandle) { await this.db(tx).invoice.update({ where: { id: invoiceId }, data: { partOrderId: orderId } }); }
  // ---- trade accounts
  async createTradeAccount(a: Parameters<PartsRepository['createTradeAccount']>[0], tx?: TxHandle) { return toTa(await this.db(tx).tradeAccount.create({ data: { sellerOrgId: a.sellerOrgId, buyerOrgId: a.buyerOrgId, paymentTermsDays: a.paymentTermsDays ?? 30 } })); }
  async findTradeAccount(id: string, tx?: TxHandle) { const r = await this.db(tx).tradeAccount.findUnique({ where: { id } }); return r ? toTa(r) : null; }
  async findTradeAccountPair(sellerOrgId: string, buyerOrgId: string, tx?: TxHandle) { const r = await this.db(tx).tradeAccount.findUnique({ where: { sellerOrgId_buyerOrgId: { sellerOrgId, buyerOrgId } } }); return r ? toTa(r) : null; }
  async listTradeAccounts(q: { sellerOrgId?: string; buyerOrgId?: string; limit: number }) { const rows = await this.prisma.tradeAccount.findMany({ where: { sellerOrgId: q.sellerOrgId, buyerOrgId: q.buyerOrgId }, take: q.limit, orderBy: { createdAt: 'desc' } }); return rows.map(toTa); }
  async updateTradeAccount(id: string, p: Parameters<PartsRepository['updateTradeAccount']>[1], tx?: TxHandle) { await this.db(tx).tradeAccount.update({ where: { id }, data: { status: p.status, creditLimit: p.creditLimit ? D(p.creditLimit) : undefined, paymentTermsDays: p.paymentTermsDays, discountBps: p.discountBps, approvedBy: p.approvedBy, approvedAt: p.approvedAt, outstanding: p.outstandingDelta ? { increment: D(p.outstandingDelta) } : undefined } }); }
  // ---- serials
  async createSerials(rows: Parameters<PartsRepository['createSerials']>[0], tx?: TxHandle) { const r = await this.db(tx).partSerial.createMany({ data: rows.map((s) => ({ catalogId: s.catalogId, serialNumber: s.serialNumber, qrToken: s.qrToken, batchCode: s.batchCode ?? undefined, issuerOrgId: s.issuerOrgId, ownerOrgId: s.ownerOrgId ?? undefined })), skipDuplicates: true }); return r.count; }
  async findSerialByToken(qrToken: string, tx?: TxHandle) { const r = await this.db(tx).partSerial.findUnique({ where: { qrToken } }); return r ? toSer(r) : null; }
  async findSerial(id: string, tx?: TxHandle) { const r = await this.db(tx).partSerial.findUnique({ where: { id } }); return r ? toSer(r) : null; }
  async listSerials(q: Parameters<PartsRepository['listSerials']>[0]) { const rows = await this.prisma.partSerial.findMany({ where: { issuerOrgId: q.issuerOrgId, ownerOrgId: q.ownerOrgId, catalogId: q.catalogId, status: q.status ? { in: q.status } : undefined, batchCode: q.batchCode }, take: q.limit, orderBy: { createdAt: 'desc' } }); return rows.map(toSer); }
  async updateSerial(id: string, p: Parameters<PartsRepository['updateSerial']>[1], tx?: TxHandle) { await this.db(tx).partSerial.update({ where: { id }, data: { status: p.status, ownerOrgId: p.ownerOrgId === undefined ? undefined : p.ownerOrgId, partOrderId: p.partOrderId === undefined ? undefined : p.partOrderId, workOrderItemId: p.workOrderItemId === undefined ? undefined : p.workOrderItemId, vehicleId: p.vehicleId === undefined ? undefined : p.vehicleId, installedAt: p.installedAt, ...(p.bumpScan ? { scanCount: { increment: 1 }, lastScannedAt: new Date() } : {}) } }); }
  // ---- warranties
  async createWarranty(w: Parameters<PartsRepository['createWarranty']>[0], tx?: TxHandle) { return toWar(await this.db(tx).warranty.create({ data: { number: w.number, qrToken: w.qrToken, issuerOrgId: w.issuerOrgId, beneficiaryUserId: w.beneficiaryUserId ?? undefined, beneficiaryOrgId: w.beneficiaryOrgId ?? undefined, vehicleId: w.vehicleId ?? undefined, partOrderId: w.partOrderId ?? undefined, workOrderItemId: w.workOrderItemId ?? undefined, partSerialId: w.partSerialId ?? undefined, installerOrgId: w.installerOrgId ?? undefined, covers: w.covers, condition: w.condition ?? undefined, coverageAr: w.coverageAr, startsAt: w.startsAt, endsAt: w.endsAt, contentSha256: w.contentSha256 } })); }
  async findWarranty(id: string) { const r = await this.prisma.warranty.findUnique({ where: { id } }); return r ? toWar(r) : null; }
  async findWarrantyByToken(qrToken: string) { const r = await this.prisma.warranty.findUnique({ where: { qrToken } }); return r ? toWar(r) : null; }
  async listWarranties(q: Parameters<PartsRepository['listWarranties']>[0]) { const rows = await this.prisma.warranty.findMany({ where: { beneficiaryUserId: q.beneficiaryUserId, beneficiaryOrgId: q.beneficiaryOrgId, vehicleId: q.vehicleId, issuerOrgId: q.issuerOrgId }, take: q.limit, orderBy: { createdAt: 'desc' } }); return rows.map(toWar); }
  async updateWarranty(id: string, p: { status?: Warranty['status'] }, tx?: TxHandle) { await this.db(tx).warranty.update({ where: { id }, data: { status: p.status } }); }
  async createClaim(c: Parameters<PartsRepository['createClaim']>[0], tx?: TxHandle) { return this.db(tx).warrantyClaim.create({ data: { warrantyId: c.warrantyId, claimantUserId: c.claimantUserId ?? undefined, descriptionAr: c.descriptionAr }, select: { id: true } }); }
  async listClaims(warrantyId: string) { const rows = await this.prisma.warrantyClaim.findMany({ where: { warrantyId }, orderBy: { createdAt: 'desc' } }); return rows.map((r) => ({ id: r.id, status: r.status, descriptionAr: r.descriptionAr, resolutionAr: r.resolutionAr, createdAt: r.createdAt })); }
  async updateClaim(id: string, p: Parameters<PartsRepository['updateClaim']>[1], tx?: TxHandle) { await this.db(tx).warrantyClaim.update({ where: { id }, data: { status: p.status as never, resolutionAr: p.resolutionAr, resolvedBy: p.resolvedBy, resolvedAt: p.resolvedAt } }); }
  // ---- group buys
  async createGroupBuy(g: Parameters<PartsRepository['createGroupBuy']>[0]) { return this.prisma.groupBuy.create({ data: { number: g.number, supplierOrgId: g.supplierOrgId, catalogId: g.catalogId, industrialZone: g.industrialZone ?? undefined, unitPrice: D(g.unitPrice), minQuantity: g.minQuantity, closesAt: g.closesAt }, select: { id: true, number: true } }); }
  async findGroupBuy(id: string, tx?: TxHandle) { const r = await this.db(tx).groupBuy.findUnique({ where: { id } }); return r ? { id: r.id, number: r.number, supplierOrgId: r.supplierOrgId, catalogId: r.catalogId, unitPrice: d0(r.unitPrice), minQuantity: r.minQuantity, committedQty: r.committedQty, closesAt: r.closesAt, status: r.status } : null; }
  async updateGroupBuy(id: string, p: { committedDelta?: number; status?: string }, tx?: TxHandle) { await this.db(tx).groupBuy.update({ where: { id }, data: { committedQty: p.committedDelta ? { increment: p.committedDelta } : undefined, status: p.status } }); }
  async findWorkOrderItem(itemId: string) { const r = await this.prisma.workOrderItem.findUnique({ where: { id: itemId }, include: { workOrder: { select: { id: true, vehicleId: true, orgId: true, customerUserId: true, customerOrgId: true } } } }); return r ? { id: r.id, workOrderId: r.workOrder.id, vehicleId: r.workOrder.vehicleId, orgId: r.workOrder.orgId, customerUserId: r.workOrder.customerUserId, customerOrgId: r.workOrder.customerOrgId } : null; }
}
