import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import type { DisputeStatus } from '@sinaaty/shared-types';
import { asTx, PrismaService } from '../../../../prisma';
import type { TxHandle } from '../../../../common/ports/unit-of-work.port';
import type { Dispute, DisputeMessage, Review } from '../../domain/dispute';
import type { DisputeRepository } from '../../domain/repositories';
const d = (v: Prisma.Decimal | null | undefined) => (v == null ? null : v.toFixed(2)); const D = (v: string) => new Prisma.Decimal(v);
type Row = Prisma.DisputeGetPayload<Record<string, never>>;
const toDispute = (r: Row): Dispute => ({ id: r.id, number: r.number, status: r.status, openedByUserId: r.openedByUserId, claimantOrgId: r.claimantOrgId, respondentOrgId: r.respondentOrgId, respondentUserId: r.respondentUserId, workOrderId: r.workOrderId, partOrderId: r.partOrderId, escrowHoldId: r.escrowHoldId, category: r.category, descriptionAr: r.descriptionAr, claimedAmount: d(r.claimedAmount), resolution: r.resolution, resolutionAmountToCustomer: d(r.resolutionAmountToCustomer), resolutionNoteAr: r.resolutionNoteAr, assignedTo: r.assignedTo, resolvedBy: r.resolvedBy, resolvedAt: r.resolvedAt, createdAt: r.createdAt });
const OPEN: DisputeStatus[] = ['open', 'under_review', 'awaiting_parties', 'escalated'];
@Injectable()
export class DisputePrismaRepository implements DisputeRepository {
  constructor(private readonly prisma: PrismaService) {}
  private db(tx?: TxHandle) { return tx ? asTx(tx) : this.prisma; }
  async nextNumber(tx?: TxHandle) { const r = await this.db(tx).$queryRaw<Array<{ n: string }>>`SELECT next_number('DS') AS n`; return r[0]!.n; }
  async create(x: Parameters<DisputeRepository['create']>[0], tx?: TxHandle) { const r = await this.db(tx).dispute.create({ data: { number: x.number, openedByUserId: x.openedByUserId, claimantOrgId: x.claimantOrgId ?? undefined, respondentOrgId: x.respondentOrgId ?? undefined, respondentUserId: x.respondentUserId ?? undefined, workOrderId: x.workOrderId ?? undefined, partOrderId: x.partOrderId ?? undefined, escrowHoldId: x.escrowHoldId ?? undefined, category: x.category, descriptionAr: x.descriptionAr, claimedAmount: x.claimedAmount ? D(x.claimedAmount) : undefined } }); return toDispute(r); }
  async findById(id: string, tx?: TxHandle) { const r = await this.db(tx).dispute.findUnique({ where: { id } }); return r ? toDispute(r) : null; }
  async findOpenByWorkOrder(workOrderId: string) { const r = await this.prisma.dispute.findFirst({ where: { workOrderId, status: { in: OPEN } }, orderBy: { createdAt: 'desc' } }); return r ? toDispute(r) : null; }
  async findOpenByPartOrder(partOrderId: string) { const r = await this.prisma.dispute.findFirst({ where: { partOrderId, status: { in: OPEN } }, orderBy: { createdAt: 'desc' } }); return r ? toDispute(r) : null; }
  async list(q: Parameters<DisputeRepository['list']>[0]) { const rows = await this.prisma.dispute.findMany({ where: { status: q.status ? { in: q.status } : undefined, openedByUserId: q.openedByUserId, assignedTo: q.assignedTo, ...(q.orgId ? { OR: [{ claimantOrgId: q.orgId }, { respondentOrgId: q.orgId }] } : {}) }, orderBy: { createdAt: 'desc' }, take: q.limit }); return rows.map(toDispute); }
  async update(id: string, p: Parameters<DisputeRepository['update']>[1], tx?: TxHandle) { await this.db(tx).dispute.update({ where: { id }, data: { status: p.status, assignedTo: p.assignedTo === undefined ? undefined : p.assignedTo, resolution: p.resolution, resolutionAmountToCustomer: p.resolutionAmountToCustomer == null ? undefined : D(p.resolutionAmountToCustomer), resolutionNoteAr: p.resolutionNoteAr, resolvedBy: p.resolvedBy, resolvedAt: p.resolvedAt } }); }
  async addMessage(m: Parameters<DisputeRepository['addMessage']>[0], tx?: TxHandle) { const r = await this.db(tx).disputeMessage.create({ data: { disputeId: m.disputeId, authorUserId: m.authorUserId, isInternal: m.isInternal, bodyAr: m.bodyAr }, include: { authorUser: { select: { fullNameAr: true } } } }); return { id: r.id, authorUserId: r.authorUserId, authorNameAr: r.authorUser.fullNameAr, isInternal: r.isInternal, bodyAr: r.bodyAr, createdAt: r.createdAt }; }
  async listMessages(disputeId: string, includeInternal: boolean): Promise<DisputeMessage[]> { const rows = await this.prisma.disputeMessage.findMany({ where: { disputeId, ...(includeInternal ? {} : { isInternal: false }) }, orderBy: { createdAt: 'asc' }, include: { authorUser: { select: { fullNameAr: true } } } }); return rows.map((r) => ({ id: r.id, authorUserId: r.authorUserId, authorNameAr: r.authorUser.fullNameAr, isInternal: r.isInternal, bodyAr: r.bodyAr, createdAt: r.createdAt })); }
  async attachMedia(disputeId: string, mediaIds: string[], label: string, tx?: TxHandle) { const r = await this.db(tx).mediaLink.createMany({ data: mediaIds.map((mediaId) => ({ mediaId, entityType: 'dispute', entityId: disputeId, label })), skipDuplicates: true }); return r.count; }
  async listMedia(disputeId: string) { const rows = await this.prisma.mediaLink.findMany({ where: { entityType: 'dispute', entityId: disputeId }, include: { media: { select: { mimeType: true } } } }); return rows.map((r) => ({ mediaId: r.mediaId, label: r.label, mimeType: r.media.mimeType })); }
  async createReview(x: Parameters<DisputeRepository['createReview']>[0], tx?: TxHandle) { const r = await this.db(tx).review.create({ data: { reviewerUserId: x.reviewerUserId, reviewerOrgId: x.reviewerOrgId ?? undefined, targetOrgId: x.targetOrgId ?? undefined, targetUserId: x.targetUserId ?? undefined, workOrderId: x.workOrderId ?? undefined, partOrderId: x.partOrderId ?? undefined, rating: x.rating, dimensions: (x.dimensions ?? {}), commentAr: x.commentAr ?? undefined } }); return { id: r.id, reviewerUserId: r.reviewerUserId, targetOrgId: r.targetOrgId, workOrderId: r.workOrderId, partOrderId: r.partOrderId, rating: r.rating, dimensions: r.dimensions, commentAr: r.commentAr, isPublic: r.isPublic, createdAt: r.createdAt } satisfies Review; }
  async listReviews(q: { targetOrgId?: string; reviewerUserId?: string; limit: number }) { const rows = await this.prisma.review.findMany({ where: { targetOrgId: q.targetOrgId, reviewerUserId: q.reviewerUserId, isPublic: q.targetOrgId ? true : undefined }, orderBy: { createdAt: 'desc' }, take: q.limit }); return rows.map((r) => ({ id: r.id, reviewerUserId: r.reviewerUserId, targetOrgId: r.targetOrgId, workOrderId: r.workOrderId, partOrderId: r.partOrderId, rating: r.rating, dimensions: r.dimensions, commentAr: r.commentAr, isPublic: r.isPublic, createdAt: r.createdAt })); }
  async refreshOrgRating(orgId: string, tx?: TxHandle) { const db = this.db(tx); const agg = await db.review.aggregate({ where: { targetOrgId: orgId, isPublic: true }, _avg: { rating: true }, _count: true }); const avg = (agg._avg.rating ?? 0).toFixed(2); await db.organization.update({ where: { id: orgId }, data: { ratingAvg: D(avg), ratingCount: agg._count } }); return { avg, count: agg._count }; }
}
