import type { Snapshot } from '../../domain/snapshot';
const esc = (s: string | number | null | undefined) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!);
const money = (s: string) => `${Number(s).toLocaleString('en-US', { minimumFractionDigits: 2 })} ر.س`;
const TERMS: Record<string, string> = { prepaid: 'دفع مقدّم', on_delivery: 'الدفع عند الاستلام', deferred: 'دفع آجل — سيصدر سند لأمر إلكتروني يُغلق تلقائياً عند سدادك', installments: 'أقساط', fleet_monthly: 'كشف شهري' };
/** Self-contained Arabic RTL page (no external assets). One screen, one big button, one sentence of legal explanation. */
export function renderApprovalPage(token: string, v: { number: string; status: string; version: number; is_current: boolean; signed: boolean; snapshot: Snapshot; phone_masked: string | null }): string {
  const s = v.snapshot; const done = v.signed || !v.is_current || v.status !== 'awaiting_approval';
  const rows = s.items.map((i) => `<div class="row"><div><div class="t">${esc(i.description_ar)}</div><div class="s">${esc(i.quantity)} × ${money(i.unit_price)}${i.warranty_days ? ` · ضمان ${i.warranty_days} يوم` : ''}</div></div><div class="p">${money(i.line_total)}</div></div>`).join('');
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>اعتماد أمر إصلاح ${esc(v.number)} — صناعتي</title>
<style>:root{--seal:#0E6B54;--soft:#DCEFE6;--ink:#12201C;--muted:#66756F;--line:#D3DCD7;--ground:#EEF2EF;--warn:#C27A12;--bad:#B4382F}*{box-sizing:border-box}body{margin:0;background:var(--ground);color:var(--ink);font-family:'IBM Plex Sans Arabic','SF Arabic','Segoe UI',system-ui,sans-serif;font-size:16px;line-height:1.7}.wrap{max-width:520px;margin:0 auto;padding:20px 16px 120px}.brand{display:flex;align-items:center;gap:10px;font-weight:700;font-size:20px;margin-bottom:14px}.brand i{width:36px;height:36px;border-radius:10px;background:var(--seal);display:inline-block}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:16px;margin-bottom:12px}h1{font-size:20px;margin:0 0 4px}.muted{color:var(--muted);font-size:14px}.row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--line)}.row:last-child{border:0}.t{font-weight:600}.s{color:var(--muted);font-size:13px}.p{white-space:nowrap;font-weight:600}.tot{display:flex;justify-content:space-between;font-size:20px;font-weight:700;margin-top:8px}.badge{display:inline-block;background:var(--soft);color:#0A4F3E;border-radius:999px;padding:3px 12px;font-size:13px;font-weight:600}.bar{position:fixed;bottom:0;left:0;right:0;background:#fff;border-top:1px solid var(--line);padding:12px 16px calc(12px + env(safe-area-inset-bottom))}.btn{display:block;width:100%;max-width:520px;margin:0 auto;border:0;border-radius:14px;padding:16px;font:inherit;font-weight:700;font-size:17px;background:var(--seal);color:#fff;cursor:pointer}.btn.ghost{background:transparent;color:var(--muted);margin-top:6px;padding:8px}.btn[disabled]{opacity:.6}.otp{display:none;margin-top:10px}.otp input{width:100%;font-size:26px;letter-spacing:8px;text-align:center;padding:12px;border:1.5px solid var(--line);border-radius:12px;direction:ltr}.msg{margin-top:8px;font-size:14px}.err{color:var(--bad)}.ok{color:var(--seal)}.done{text-align:center;padding:24px 0}.done .big{font-size:48px}</style></head><body><div class="wrap">
<div class="brand"><i></i>صناعتي</div>
<div class="card"><h1>أمر إصلاح ${esc(v.number)}</h1><div class="muted">${esc(s.org.name_ar)} · النسخة ${v.version}${s.reason_ar ? ` · سبب التعديل: ${esc(s.reason_ar)}` : ''}</div><div class="muted">${esc([[s.vehicle.make_ar, s.vehicle.model_ar, s.vehicle.year].filter(Boolean).join(' '), s.vehicle.plate].filter(Boolean).join(' · '))}</div></div>
<div class="card">${rows}<div class="row"><div class="s">ضريبة القيمة المضافة 15%</div><div class="p">${money(s.totals.vat)}</div></div><div class="tot"><span>الإجمالي</span><span>${money(s.totals.total)}</span></div></div>
<div class="card"><span class="badge">${esc(TERMS[s.payment_terms] ?? s.payment_terms)}</span>${Number(s.deposit_required) > 0 ? `<div class="muted" style="margin-top:6px">دفعة مقدّمة ${money(s.deposit_required)} — تبقى محفوظة حتى تستلم سيارتك.</div>` : ''}<div class="muted" style="margin-top:8px">توقيعك يثبّت هذا السعر — لا يمكن للورشة زيادته بدون موافقتك، وأي تعديل يصلك كنسخة جديدة.</div></div>
${done ? `<div class="card done"><div class="big">${v.signed ? '✅' : 'ℹ️'}</div><b>${v.signed ? 'تم اعتماد هذه النسخة' : v.status === 'cancelled' ? 'أمر الإصلاح ملغى' : !v.is_current ? 'هناك نسخة أحدث — افتح آخر رابط وصلك' : 'هذا الأمر لم يعد بانتظار الاعتماد'}</b><div class="muted">لمتابعة سيارتك بالصور حمّل تطبيق صناعتي.</div></div>` : ''}
</div>
${done ? '' : `<div class="bar"><div id="step1"><div class="muted" style="text-align:center;margin-bottom:8px">سيصلك رمز تحقق على <bdi dir="ltr">${esc(v.phone_masked ?? 'جوالك')}</bdi></div><button class="btn" id="go">اعتماد أمر الإصلاح</button><button class="btn ghost" id="decline">لا أوافق</button></div>
<div class="otp" id="step2"><input id="code" inputmode="numeric" maxlength="6" placeholder="••••••" autocomplete="one-time-code"><button class="btn" id="confirm" style="margin-top:8px">تأكيد الاعتماد</button><div class="msg" id="msg"></div></div></div>
<script>(function(){var T=${JSON.stringify(token)},b='/v1/approve/'+encodeURIComponent(T),m=document.getElementById('msg');function post(p,body){return fetch(b+p,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})}).then(function(r){return r.json().then(function(j){if(!r.ok)throw j;return j})})}
document.getElementById('go').onclick=function(){this.disabled=true;post('/otp').then(function(j){document.getElementById('step1').style.display='none';document.getElementById('step2').style.display='block';document.getElementById('code').focus();if(j.debug_code){document.getElementById('code').value=j.debug_code}}).catch(function(e){m.className='msg err';m.textContent=e.message_ar||'تعذّر الإرسال';document.getElementById('go').disabled=false})};
document.getElementById('confirm').onclick=function(){var c=document.getElementById('code').value;if(!/^\\d{6}$/.test(c)){m.className='msg err';m.textContent='أدخل الرمز المكوّن من 6 أرقام';return}this.disabled=true;post('/complete',{code:c}).then(function(){document.body.innerHTML='<div class="wrap"><div class="brand"><i></i>صناعتي</div><div class="card done"><div class="big">✅</div><b>تم الاعتماد — الورشة تبدأ العمل الآن</b><div class="muted">ستصلك إشعارات بالصور. حمّل تطبيق صناعتي لمتابعة سيارتك.</div></div></div>'}).catch(function(e){m.className='msg err';m.textContent=e.message_ar||'رمز غير صحيح';document.getElementById('confirm').disabled=false})};
document.getElementById('decline').onclick=function(){var r=prompt('سبب عدم الموافقة (اختياري)')||'لا أوافق على السعر';post('/decline',{reason_ar:r}).then(function(){location.reload()}).catch(function(e){m.className='msg err';m.textContent=e.message_ar||'تعذّر الإلغاء'})};})();</script>`}
</body></html>`;
}
