import { Inject, Injectable } from '@nestjs/common';
import { AppError } from '../../../common/errors';
import { AuditLogWriter } from '../../../common/audit';
import { OutboxWriter } from '../../../common/outbox';
import { UNIT_OF_WORK, type UnitOfWork } from '../../../common/ports/unit-of-work.port';
import type { AuthUser } from '../../identity/domain/auth-user';
import { isPlatformStaff, membership } from '../../identity/domain/auth-user';
import { ORGANIZATION_REPOSITORY, type OrganizationRepository } from '../../organizations/domain/repositories';
import type { Warranty } from '../domain/parts';
import { PARTS_REPOSITORY, type PartsRepository } from '../domain/repositories';
import type { ClaimDto, ClaimResolveDto, GroupBuyDto, GroupBuyJoinDto } from './dto/parts.dto';
import { OrdersUseCases } from './orders.use-cases';

@Injectable()
export class WarrantiesUseCases {
  constructor(@Inject(PARTS_REPOSITORY) private readonly repo: PartsRepository, @Inject(ORGANIZATION_REPOSITORY) private readonly orgs: OrganizationRepository, @Inject(UNIT_OF_WORK) private readonly uow: UnitOfWork, private readonly audit: AuditLogWriter, private readonly outbox: OutboxWriter, private readonly orders: OrdersUseCases) {}
  private canRead(w: Warranty, u: AuthUser) { return isPlatformStaff(u) || w.beneficiaryUserId === u.id || (!!w.beneficiaryOrgId && !!membership(u, w.beneficiaryOrgId)) || !!membership(u, w.issuerOrgId) || (!!w.installerOrgId && !!membership(u, w.installerOrgId)); }
  async mine(u: AuthUser, orgId?: string) { if (orgId && !membership(u, orgId) && !isPlatformStaff(u)) throw new AppError('FORBIDDEN'); return this.repo.listWarranties(orgId ? { beneficiaryOrgId: orgId, limit: 200 } : { beneficiaryUserId: u.id, limit: 200 }); }
  async issued(u: AuthUser, orgId: string) { if (!membership(u, orgId) && !isPlatformStaff(u)) throw new AppError('FORBIDDEN'); return this.repo.listWarranties({ issuerOrgId: orgId, limit: 500 }); }
  async get(u: AuthUser, id: string) { const w = await this.repo.findWarranty(id); if (!w) throw new AppError('NOT_FOUND'); if (!this.canRead(w, u)) throw new AppError('FORBIDDEN'); const issuer = await this.orgs.findById(w.issuerOrgId); return { ...w, issuer_ar: issuer?.tradeNameAr ?? issuer?.legalNameAr ?? null, claims: await this.repo.listClaims(id), expired: w.endsAt.getTime() < Date.now() }; }
  /** Public certificate check by QR token (no personal data). */
  async publicByToken(qrToken: string) { const w = await this.repo.findWarrantyByToken(qrToken); if (!w) throw new AppError('NOT_FOUND'); const issuer = await this.orgs.findById(w.issuerOrgId); return { number: w.number, covers: w.covers, coverage_ar: w.coverageAr, starts_at: w.startsAt, ends_at: w.endsAt, status: w.status, valid: w.status === 'active' && w.endsAt.getTime() >= Date.now(), issuer_ar: issuer?.tradeNameAr ?? issuer?.legalNameAr ?? null, content_sha256: w.contentSha256 }; }
  async claim(u: AuthUser, id: string, dto: ClaimDto) { const w = await this.repo.findWarranty(id); if (!w) throw new AppError('NOT_FOUND'); if (!(w.beneficiaryUserId === u.id || (w.beneficiaryOrgId && membership(u, w.beneficiaryOrgId)))) throw new AppError('FORBIDDEN'); if (w.status !== 'active' || w.endsAt.getTime() < Date.now()) throw new AppError('CONFLICT', { messageAr: 'الضمان غير ساري.', messageEn: 'Warranty is not active.' }); return this.uow.run(async (tx) => { const c = await this.repo.createClaim({ warrantyId: id, claimantUserId: u.id, descriptionAr: dto.description_ar }, tx); await this.repo.updateWarranty(id, { status: 'claimed' }, tx); await this.audit.write(tx, { action: 'warranty.claim', entityType: 'warranty', entityId: id, orgId: w.issuerOrgId, actorUserId: u.id, after: { claim: c.id } }); await this.outbox.publish(tx, { eventType: 'WarrantyClaimOpened', aggregateType: 'warranty', aggregateId: id, payload: { number: w.number, issuerOrgId: w.issuerOrgId, installerOrgId: w.installerOrgId, claimId: c.id, beneficiaryUserId: w.beneficiaryUserId, beneficiaryOrgId: w.beneficiaryOrgId } }); return { claim_id: c.id }; }); }
  async resolveClaim(u: AuthUser, warrantyId: string, claimId: string, dto: ClaimResolveDto) { const w = await this.repo.findWarranty(warrantyId); if (!w) throw new AppError('NOT_FOUND'); if (!membership(u, w.issuerOrgId) && !isPlatformStaff(u)) throw new AppError('FORBIDDEN'); await this.uow.run(async (tx) => { await this.repo.updateClaim(claimId, { status: dto.status, resolutionAr: dto.resolution_ar, resolvedBy: u.id, resolvedAt: dto.status === 'under_review' ? undefined : new Date() }, tx); const ws = dto.status === 'approved_replace' ? 'replaced' : dto.status === 'approved_refund' ? 'refunded' : dto.status === 'rejected' || dto.status === 'closed' ? 'active' : undefined; if (ws) await this.repo.updateWarranty(warrantyId, { status: ws }, tx); await this.audit.write(tx, { action: `warranty_claim.${dto.status}`, entityType: 'warranty', entityId: warrantyId, orgId: w.issuerOrgId, actorUserId: u.id, after: { claim: claimId, resolution: dto.resolution_ar ?? null } }); }); return this.get(u, warrantyId); }
  // ---- group buys (minimal): supplier opens, workshops join with quantity; reaching min_quantity flips to 'reached' (orders placed at fulfilment — backlog).
  async openGroupBuy(u: AuthUser, dto: GroupBuyDto) { if (!membership(u, dto.org_id) && !isPlatformStaff(u)) throw new AppError('FORBIDDEN'); if (!(await this.repo.findCatalog(dto.catalog_id))) throw new AppError('NOT_FOUND'); const number = await this.repo.nextNumber('GB'); return this.repo.createGroupBuy({ number, supplierOrgId: dto.org_id, catalogId: dto.catalog_id, industrialZone: dto.industrial_zone ?? null, unitPrice: dto.unit_price, minQuantity: dto.min_quantity, closesAt: new Date(Date.now() + dto.closes_in_hours * 3_600_000) }); }
  async joinGroupBuy(u: AuthUser, id: string, dto: GroupBuyJoinDto) { if (!membership(u, dto.org_id) && !isPlatformStaff(u)) throw new AppError('FORBIDDEN'); return this.uow.run(async (tx) => { const g = await this.repo.findGroupBuy(id, tx); if (!g) throw new AppError('NOT_FOUND'); if (g.status !== 'open' || g.closesAt.getTime() < Date.now()) throw new AppError('CONFLICT', { messageAr: 'الشراء الجماعي مغلق.', messageEn: 'Group buy is closed.' }); const total = g.committedQty + dto.quantity; await this.repo.updateGroupBuy(id, { committedDelta: dto.quantity, status: total >= g.minQuantity ? 'reached' : undefined }, tx); await this.audit.write(tx, { action: 'group_buy.join', entityType: 'group_buy', entityId: id, orgId: dto.org_id, actorUserId: u.id, after: { quantity: dto.quantity, committed: total } }); return { ...(await this.repo.findGroupBuy(id, tx))!, reached: total >= g.minQuantity }; }); }
  async getGroupBuy(id: string) { const g = await this.repo.findGroupBuy(id); if (!g) throw new AppError('NOT_FOUND'); return g; }
  /** Escrow of confirm() lives in OrdersUseCases; exposed here for the controller's symmetry. */
  confirmOrder(u: AuthUser, id: string) { return this.orders.confirm(u, id); }
}
