import type { BidStatus, PartCondition, PartOrderSource, PartOrderStatus, PartRequestStatus, PartSerialStatus, PaymentTerms, TradeAccountStatus, WarrantyStatus } from '@sinaaty/shared-types';

export interface CatalogPart { id: string; brandId: number; brandNameAr: string | null; partNumber: string; oemNumbers: string[]; categoryId: number | null; nameAr: string; nameEn: string | null; isSerialized: boolean; createdByOrgId: string | null }
export interface Fitment { id: string; catalogId: string; makeId: number; modelId: number | null; yearFrom: number | null; yearTo: number | null; engineCode: string | null }
export interface InventoryItem { id: string; orgId: string; catalogId: string | null; categoryId: number | null; makeId: number | null; modelId: number | null; yearFrom: number | null; yearTo: number | null; partNumber: string | null; condition: PartCondition; titleAr: string; price: string | null; tradePrice: string | null; quantity: number; reservedQty: number; donorVin: string | null; warrantyDays: number; leadTimeHours: number | null; externalSku: string | null; isActive: boolean }
export interface PartRequest { id: string; number: string; requesterUserId: string | null; requesterOrgId: string | null; workOrderId: string | null; vehicleId: string | null; vin: string | null; categoryId: number | null; partNameAr: string; partNumber: string | null; descriptionAr: string | null; acceptedConditions: PartCondition[]; quantity: number; searchRadiusKm: number; biddingEndsAt: Date; status: PartRequestStatus; awardedBidId: string | null; createdAt: Date }
export interface PartBid { id: string; requestId: string; supplierOrgId: string; inventoryId: string | null; condition: PartCondition; unitPrice: string; quantity: number; vatRate: string; deliveryFee: string; deliveryEtaHours: number | null; warrantyDays: number; warrantyTermsAr: string | null; donorVin: string | null; notesAr: string | null; status: BidStatus; createdAt: Date; updatedAt: Date }
export interface PartOrderItem { id: string; inventoryId: string | null; catalogId: string | null; descriptionAr: string; condition: PartCondition; quantity: number; unitPrice: string; vatRate: string; lineTotal: string; warrantyDays: number }
export interface PartOrder { id: string; number: string; source: PartOrderSource; requestId: string | null; bidId: string | null; tradeAccountId: string | null; buyerUserId: string | null; buyerOrgId: string | null; supplierOrgId: string; workOrderId: string | null; paymentTerms: PaymentTerms; status: PartOrderStatus; subtotal: string; deliveryFee: string; vatAmount: string; total: string; shippedAt: Date | null; deliveredAt: Date | null; installedAt: Date | null; confirmedAt: Date | null; autoConfirmAt: Date | null; createdAt: Date; items: PartOrderItem[] }
export interface TradeAccount { id: string; sellerOrgId: string; buyerOrgId: string; status: TradeAccountStatus; creditLimit: string; outstanding: string; paymentTermsDays: number; discountBps: number; requiresNote: boolean; approvedBy: string | null; approvedAt: Date | null; createdAt: Date }
export interface PartSerial { id: string; catalogId: string; serialNumber: string; qrToken: string; batchCode: string | null; issuerOrgId: string; ownerOrgId: string | null; status: PartSerialStatus; partOrderId: string | null; workOrderItemId: string | null; vehicleId: string | null; installedAt: Date | null; scanCount: number; lastScannedAt: Date | null }
export interface Warranty { id: string; number: string; qrToken: string; issuerOrgId: string; beneficiaryUserId: string | null; beneficiaryOrgId: string | null; vehicleId: string | null; partOrderId: string | null; workOrderItemId: string | null; partSerialId: string | null; installerOrgId: string | null; covers: string; condition: PartCondition | null; coverageAr: string; startsAt: Date; endsAt: Date; status: WarrantyStatus; contentSha256: string }

/** Reverse-auction request lifecycle. */
export const REQUEST_TRANSITIONS: Record<PartRequestStatus, PartRequestStatus[]> = { open: ['bidding', 'expired', 'cancelled'], bidding: ['awarded', 'expired', 'cancelled'], awarded: ['fulfilled', 'cancelled'], fulfilled: [], expired: [], cancelled: [] };
/** Part order lifecycle: prepaid orders wait for payment; deferred (trade account) skip straight to 'paid' (note issued). */
export const ORDER_TRANSITIONS: Record<PartOrderStatus, PartOrderStatus[]> = { pending_payment: ['paid', 'cancelled'], paid: ['preparing', 'shipped', 'cancelled'], preparing: ['shipped', 'cancelled'], shipped: ['delivered'], delivered: ['installed', 'confirmed', 'returned', 'disputed'], installed: ['confirmed', 'disputed'], confirmed: ['disputed'], returned: [], cancelled: [], disputed: ['confirmed', 'returned'] };
export const canRequest = (f: PartRequestStatus, t: PartRequestStatus) => REQUEST_TRANSITIONS[f].includes(t);
export const canOrder = (f: PartOrderStatus, t: PartOrderStatus) => ORDER_TRANSITIONS[f].includes(t);
export const SUPPLIER_ORG_TYPES = ['scrapyard', 'parts_dealer', 'parts_distributor', 'parts_brand_agent'] as const;
/** Serial scanned this many times, or scanned after being installed elsewhere → counterfeit/duplicate alert. */
export const SERIAL_SCAN_ALERT_THRESHOLD = 5;
/** Credit check for a deferred order on a trade account. */
export const creditAllows = (a: Pick<TradeAccount, 'status' | 'creditLimit' | 'outstanding'>, orderTotal: string) => a.status === 'active' && Number(a.outstanding) + Number(orderTotal) <= Number(a.creditLimit) + 1e-9;
/** Year overlap for fitments/inventory ranges (null = open-ended). */
export const yearFits = (from: number | null, to: number | null, year: number | null) => year == null || ((from == null || from <= year) && (to == null || to >= year));
