import type { NotificationChannel } from '@sinaaty/shared-types';
/**
 * Notification templates — Arabic first, plain words (Simplicity charter §5.0). Placeholders: {name}.
 * `channels` = default delivery; in_app is always stored. Formal/legal messages also go by SMS.
 */
export interface Template { code: string; channels: NotificationChannel[]; titleAr: string; titleEn: string; bodyAr: string; bodyEn: string; deepLink?: string }
/**
 * **الرابط العميق يتبع جمهور القالب لا موضوع الحدث.** الشاشة الواحدة لها وجهان: `/work-orders/:id`
 * للعميل (اعتمد · ادفع · استلمت) و`/ws/orders/:id` للورشة (استلم · افحص · سلّم). قالبٌ يذهب لطاقم
 * المنشأة ويحمل مسار العميل يُنزل صاحبه على شاشة بلا الزرّ الذي وُجد الإشعار لأجله — وهو ما كان
 * يحدث في ثلاثة قوالب، منها إشعار «عميل قريب يحتاج إصلاحاً» نفسه.
 */
export const TEMPLATES: Record<string, Template> = {
  'wo.abandoned.notice': { code: 'wo.abandoned.notice', channels: ['push', 'sms'], titleAr: 'سيارتك جاهزة بانتظار الاستلام', titleEn: 'Your car is ready and waiting', bodyAr: 'أمر {number}: سيارتك جاهزة منذ {days} يوماً. يرجى استلامها وسداد {total} ر.س.{storage} — بعد المهلة قد تُعد السيارة مهجورة نظاماً.', bodyEn: 'Order {number}: your car has been ready for {days} days. Please collect it and settle SAR {total}.{storage}', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.abandoned.declared': { code: 'wo.abandoned.declared', channels: ['push', 'sms'], titleAr: 'إشعار: اعتبار المركبة مهجورة', titleEn: 'Notice: vehicle declared abandoned', bodyAr: 'أمر {number}: بعد انتهاء المهلة والإنذارات، سُجّلت المركبة كمهجورة. المطالبة {total} ر.س (إصلاح {repair} + حفظ {storage}). تواصل مع الورشة فوراً.', bodyEn: 'Order {number}: after the notice period the vehicle was recorded as abandoned. Claim SAR {total}.', deepLink: 'sinaaty://work-orders/{id}' },
  'accident.linked': { code: 'accident.linked', channels: ['push'], titleAr: 'ربطنا تقرير الحادث بإصلاح سيارتك', titleEn: 'Accident report linked to your repair', bodyAr: 'تقرير {ref}: التأمين ({insurer}) اعتمد {approved} ر.س. المتوقع عليك {customer} ر.س. — التفاصيل في أمر {number}.', bodyEn: 'Report {ref}: insurer ({insurer}) approved SAR {approved}. Your expected share is SAR {customer} — details in order {number}.', deepLink: 'sinaaty://work-orders/{id}' },
  'accident.updated': { code: 'accident.updated', channels: ['push'], titleAr: 'تحديث على تقرير الحادث', titleEn: 'Accident report updated', bodyAr: 'تقرير {ref}: {status}{approved_note}', bodyEn: 'Report {ref}: {status}{approved_note}', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.created': { code: 'wo.created', channels: ['push'], titleAr: 'تم استلام سيارتك', titleEn: 'Your car has been received', bodyAr: '{org} استلمت سيارتك {vehicle} — أمر إصلاح {number}. ستصلك التفاصيل والسعر لاعتمادها.', bodyEn: '{org} received your {vehicle} — work order {number}. You will get the details and price to approve.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.awaiting_approval': { code: 'wo.awaiting_approval', channels: ['push', 'sms'], titleAr: 'أمر إصلاح بانتظار اعتمادك', titleEn: 'Repair order awaiting your approval', bodyAr: '{org}: أمر {number} بقيمة {total} ر.س. راجعه واعتمده — لا يبدأ العمل قبل موافقتك.{link}', bodyEn: '{org}: order {number} for SAR {total}. Review and approve — work starts only after your approval.{link}', deepLink: 'sinaaty://work-orders/{id}/approve' },
  'wo.approved': { code: 'wo.approved', channels: ['push'], titleAr: 'العميل اعتمد الأمر', titleEn: 'Customer approved the order', bodyAr: 'تم اعتماد أمر {number} (النسخة {version}) — ابدأ التنفيذ.{deferred}', bodyEn: 'Order {number} (v{version}) approved — start work.{deferred}', deepLink: 'sinaaty://ws/orders/{id}' },
  'wo.status.awaiting_parts': { code: 'wo.status.awaiting_parts', channels: ['push'], titleAr: 'بانتظار القطع', titleEn: 'Waiting for parts', bodyAr: 'أمر {number}: بانتظار وصول القطع.', bodyEn: 'Order {number}: waiting for parts.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.status.in_progress': { code: 'wo.status.in_progress', channels: ['push'], titleAr: 'بدأ العمل على سيارتك', titleEn: 'Work started on your car', bodyAr: 'أمر {number}: جاري التنفيذ. تابع الصور لحظياً من التطبيق.', bodyEn: 'Order {number}: in progress. Follow live photos in the app.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.status.quality_check': { code: 'wo.status.quality_check', channels: ['push'], titleAr: 'فحص الجودة', titleEn: 'Quality check', bodyAr: 'أمر {number}: في مرحلة فحص الجودة قبل التسليم.', bodyEn: 'Order {number}: quality check before delivery.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.status.ready': { code: 'wo.status.ready', channels: ['push', 'sms'], titleAr: 'سيارتك جاهزة للاستلام', titleEn: 'Your car is ready', bodyAr: 'أمر {number}: سيارتك جاهزة لدى {org}. يمكنك الدفع من التطبيق قبل الحضور.', bodyEn: 'Order {number}: your car is ready at {org}. You can pay in the app before you arrive.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.status.delivered': { code: 'wo.status.delivered', channels: ['push'], titleAr: 'تم تسليم سيارتك', titleEn: 'Vehicle delivered', bodyAr: 'أمر {number}: تم التسليم. المبلغ محفوظ لدينا حتى تؤكد الاستلام (أو خلال 72 ساعة).', bodyEn: 'Order {number}: delivered. Funds stay held until you confirm receipt (or 72h).', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.status.closed': { code: 'wo.status.closed', channels: ['push'], titleAr: 'أُغلق أمر الإصلاح', titleEn: 'Repair order closed', bodyAr: 'أمر {number} أُغلق. شكراً لك — قيّم تجربتك مع {org}.', bodyEn: 'Order {number} closed. Thank you — rate your experience with {org}.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.status.cancelled': { code: 'wo.status.cancelled', channels: ['push', 'sms'], titleAr: 'أُلغي أمر الإصلاح', titleEn: 'Repair order cancelled', bodyAr: 'أمر {number} أُلغي{reason}.', bodyEn: 'Order {number} was cancelled{reason}.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.status.disputed': { code: 'wo.status.disputed', channels: ['push', 'sms'], titleAr: 'تم فتح نزاع', titleEn: 'Dispute opened', bodyAr: 'أمر {number}: تم فتح نزاع وتجميد المبلغ حتى القرار.', bodyEn: 'Order {number}: a dispute was opened; funds are frozen until resolved.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.status.abandoned': { code: 'wo.status.abandoned', channels: ['push', 'sms'], titleAr: 'إشعار: بدء إجراءات المركبة المتروكة', titleEn: 'Notice: abandoned vehicle procedure started', bodyAr: 'أمر {number}: سيارتك لم تُستلم بعد المهلة النظامية. تواصل مع {org} فوراً.', bodyEn: 'Order {number}: your vehicle was not collected within the legal period. Contact {org} immediately.', deepLink: 'sinaaty://work-orders/{id}' },
  'wo.change_order': { code: 'wo.change_order', channels: ['push', 'sms'], titleAr: 'تعديل على أمر الإصلاح يحتاج اعتمادك', titleEn: 'Change to your repair order needs approval', bodyAr: '{org} تقترح تعديلاً على أمر {number} (النسخة {version}) — الإجمالي الجديد {total} ر.س. لن يُنفَّذ قبل موافقتك.{link}', bodyEn: '{org} proposes a change to order {number} (v{version}) — new total SAR {total}. Nothing changes until you approve.{link}', deepLink: 'sinaaty://work-orders/{id}/approve' },
  // التشليح والوكالة كانا خارج الإشعار تماماً: الطلب يُسجَّل ويُبَثّ حياً، ومن أغلق تطبيقه لا
  // يعلم. سوقُ القطع من طرف واحد ليس سوقاً — كما سوق الإصلاح تماماً.
  'part.request.nearby': { code: 'part.request.nearby', channels: ['push'], titleAr: 'طلب قطعة قريب منك', titleEn: 'A parts request near you', bodyAr: '«{part}»{car} — على بعد {distance}. قدّم سعرك قبل {ends}.', bodyEn: '"{part}"{car} — {distance} away. Bid before {ends}.', deepLink: 'sinaaty://parts/requests/{id}' },
  'service.request.nearby': { code: 'service.request.nearby', channels: ['push'], titleAr: 'عميل قريب يحتاج إصلاحاً', titleEn: 'A nearby customer needs a repair', bodyAr: '«{title}» — على بعد {distance}. ادرس الحالة وقدّم عرضك: تشخيص وسعر، أو معاينة مجانية.', bodyEn: '"{title}" — {distance} away. Review and offer: a diagnosis and price, or a free inspection.', deepLink: 'sinaaty://ws/service-requests/{id}' },
  'service.offer.received': { code: 'service.offer.received', channels: ['push'], titleAr: 'وصلك عرض على طلبك', titleEn: 'You received an offer', bodyAr: '{org} ردّت على «{title}»{price_note}. قارن العروض واختر.', bodyEn: '{org} answered "{title}"{price_note}. Compare and choose.', deepLink: 'sinaaty://service-requests/{id}' },
  'service.offer.accepted': { code: 'service.offer.accepted', channels: ['push', 'sms'], titleAr: 'العميل اختار عرضكم', titleEn: 'The customer chose your offer', bodyAr: 'طلب {number}: العميل قبل عرضكم — فُتح أمر عمل {wo}. استقبلوه وابدؤوا الفحص.', bodyEn: 'Request {number}: your offer was accepted — work order {wo} opened.', deepLink: 'sinaaty://ws/orders/{wo_id}' },
  'service.request.quiet': { code: 'service.request.quiet', channels: ['push'], titleAr: 'العروض قليلة — وسّع نطاق البحث؟', titleEn: 'Few offers — widen your search?', bodyAr: '«{title}» وصله {offers} من العروض حتى الآن. وسّع النطاق بنقرة ليصل طلبك ورشاً أبعد قليلاً.', bodyEn: '"{title}" got {offers} offers so far. Widen the radius so slightly farther workshops can answer.', deepLink: 'sinaaty://service-requests/{id}' },
  'invoice.issued': { code: 'invoice.issued', channels: ['push', 'email'], titleAr: 'صدرت فاتورتك', titleEn: 'Your invoice is ready', bodyAr: 'فاتورة {number} من {org} بقيمة {total} ر.س. ادفع من التطبيق بمدى أو Apple Pay.', bodyEn: 'Invoice {number} from {org} for SAR {total}. Pay in the app with Mada or Apple Pay.', deepLink: 'sinaaty://invoices/{id}' },
  'transport.invoice.issued': { code: 'transport.invoice.issued', channels: ['push', 'email'], titleAr: 'فاتورة سطحتك جاهزة', titleEn: 'Your tow invoice is ready', bodyAr: 'وصلت سيارتك وسُلّمت بنجاح. فاتورة {number} بقيمة {total} ر.س — ادفع من التطبيق بمدى أو Apple Pay.', bodyEn: 'Your car was delivered. Invoice {number} for SAR {total} — pay in the app with Mada or Apple Pay.', deepLink: 'sinaaty://tow/{job_id}' },
  'approval.requested': { code: 'approval.requested', channels: ['push'], titleAr: 'طلب استرداد بانتظار الاعتماد', titleEn: 'Refund request awaiting approval', bodyAr: 'زميلك طلب استرداد {amount} ر.س من مبلغ محفوظ — يحتاج اعتماد شخص آخر قبل التنفيذ.', bodyEn: 'A colleague requested a refund of SAR {amount} from held funds — a second approval is required.', deepLink: 'sinaaty://admin/approvals' },
  'dispute.money.decided': { code: 'dispute.money.decided', channels: ['push'], titleAr: 'قرار نزاع حرّك أموالاً', titleEn: 'A dispute decision moved money', bodyAr: 'نزاع {number}: {to_customer} ر.س للعميل و{to_provider} ر.س للمزوّد — للاطلاع البعدي من فريق المالية.', bodyEn: 'Dispute {number}: SAR {to_customer} to the customer, SAR {to_provider} to the provider.', deepLink: 'sinaaty://admin/disputes/{id}' },
  'invoice.paid': { code: 'invoice.paid', channels: ['push'], titleAr: 'تم سداد الفاتورة', titleEn: 'Invoice paid', bodyAr: 'فاتورة {number}: استلمنا {amount} ر.س. المبلغ محفوظ ويُحوَّل لمحفظتك بعد تأكيد العميل أو خلال 72 ساعة.', bodyEn: 'Invoice {number}: SAR {amount} received. Held and released to your wallet after customer confirmation or 72h.', deepLink: 'sinaaty://invoices/{id}' },
  'invoice.paid.customer': { code: 'invoice.paid.customer', channels: ['push', 'email'], titleAr: 'شكراً — تم الدفع', titleEn: 'Thank you — payment received', bodyAr: 'فاتورة {number}: تم دفع {amount} ر.س بنجاح.', bodyEn: 'Invoice {number}: SAR {amount} paid successfully.', deepLink: 'sinaaty://invoices/{id}' },
  'escrow.released': { code: 'escrow.released', channels: ['push'], titleAr: 'تم تحويل المستحقات لمحفظتك', titleEn: 'Funds released to your wallet', bodyAr: '{net} ر.س أصبحت متاحة في محفظتك (أمر {wo}).', bodyEn: 'SAR {net} is now available in your wallet (order {wo}).', deepLink: 'sinaaty://ws/wallet' },
  'dispute.opened': { deepLink: 'sinaaty://disputes/{id}', code: 'dispute.opened', channels: ['push', 'sms'], titleAr: 'فُتح نزاع', titleEn: 'A dispute was opened', bodyAr: 'نزاع {number} على {ref} — المبلغ محفوظ ومجمّد حتى يُحسم. أضف ردّك وأدلتك من التطبيق.', bodyEn: 'Dispute {number} on {ref} — the amount is frozen until it is resolved. Add your response and evidence in the app.' },
  'dispute.message': { deepLink: 'sinaaty://disputes/{id}', code: 'dispute.message', channels: ['push'], titleAr: 'رد جديد على النزاع', titleEn: 'New message on the dispute', bodyAr: 'وصل رد جديد في نزاع {number}.', bodyEn: 'A new message was posted on dispute {number}.' },
  'dispute.resolved': { deepLink: 'sinaaty://disputes/{id}', code: 'dispute.resolved', channels: ['push', 'sms'], titleAr: 'صدر قرار النزاع', titleEn: 'Dispute decision issued', bodyAr: 'نزاع {number}: {decision}. للعميل {to_customer} ر.س وللمزوّد {to_provider} ر.س.', bodyEn: 'Dispute {number}: {decision}. Customer {to_customer} SAR, provider {to_provider} SAR.' },
  'transport.assigned': { deepLink: 'sinaaty://tow/{id}', code: 'transport.assigned', channels: ['push', 'sms'], titleAr: 'السطحة في الطريق', titleEn: 'The tow truck is on its way', bodyAr: 'قبل السائق {driver} مهمتك {number} — لوحة الشاحنة {plate}. تابع موقعه لحظياً من التطبيق.', bodyEn: 'Driver {driver} accepted job {number} — truck {plate}. Track it live in the app.' },
  'transport.status': { deepLink: 'sinaaty://tow/{id}', code: 'transport.status', channels: ['push'], titleAr: 'تحديث النقل', titleEn: 'Transport update', bodyAr: 'مهمة {number}: {status}.', bodyEn: 'Job {number}: {status}.' },
  'transport.proof': { deepLink: 'sinaaty://tow/{id}', code: 'transport.proof', channels: ['sms'], titleAr: 'رمز تأكيد الاستلام', titleEn: 'Delivery confirmation code', bodyAr: 'رمز تسليم مهمة {number}: {code} — أعطه للسائق عند استلام سيارتك.', bodyEn: 'Delivery code for job {number}: {code} — give it to the driver on handover.' },
  'transport.delivered': { deepLink: 'sinaaty://tow/{id}', code: 'transport.delivered', channels: ['push'], titleAr: 'تم تسليم سيارتك', titleEn: 'Your car was delivered', bodyAr: 'اكتملت مهمة النقل {number} بإثبات تسليم مصوَّر. التكلفة {price} ر.س.', bodyEn: 'Transport {number} completed with photo proof. Cost SAR {price}.' },
  'note.issued': { code: 'note.issued', channels: ['push', 'sms'], titleAr: 'صدر سند لأمر إلكتروني', titleEn: 'Electronic promissory note issued', bodyAr: 'سند {number} بقيمة {amount} ر.س لصالح {org}، يستحق في {due}. يُغلق تلقائياً فور سدادك الفاتورة.', bodyEn: 'Note {number} for SAR {amount} in favour of {org}, due {due}. It closes automatically when you pay the invoice.', deepLink: 'sinaaty://notes/{id}' },
  'note.issued.creditor': { code: 'note.issued.creditor', channels: ['push'], titleAr: 'حقك مضمون بسند', titleEn: 'Your receivable is secured by a note', bodyAr: 'سند {number} بقيمة {amount} ر.س صدر باسم العميل — استحقاق {due}.', bodyEn: 'Note {number} for SAR {amount} issued against the customer — due {due}.', deepLink: 'sinaaty://notes/{id}' },
  'note.closed': { code: 'note.closed', channels: ['push', 'sms'], titleAr: 'أُغلق السند وصدرت مخالصتك', titleEn: 'Note closed — settlement issued', bodyAr: 'تم سداد السند {number} بالكامل وإغلاقه، وصدرت مخالصة رقم {settlement}. ذمتك بريئة.', bodyEn: 'Note {number} fully paid and closed; settlement {settlement} issued. You are cleared.', deepLink: 'sinaaty://notes/{id}' },
  'note.partially_settled': { code: 'note.partially_settled', channels: ['push'], titleAr: 'سداد جزئي للسند', titleEn: 'Partial payment on note', bodyAr: 'سند {number}: المتبقي {outstanding} ر.س.', bodyEn: 'Note {number}: remaining SAR {outstanding}.', deepLink: 'sinaaty://notes/{id}' },
  'note.dunning.reminder': { code: 'note.dunning.reminder', channels: ['push'], titleAr: 'تذكير بسند مستحق', titleEn: 'Reminder: note is due', bodyAr: 'سند {number} بقيمة {outstanding} ر.س تجاوز تاريخ استحقاقه ({due}). سدّد من التطبيق لتجنّب الإجراءات النظامية.', bodyEn: 'Note {number} for SAR {outstanding} is past due ({due}). Pay in the app to avoid legal steps.', deepLink: 'sinaaty://notes/{id}' },
  'note.dunning.formal': { code: 'note.dunning.formal', channels: ['push', 'sms'], titleAr: 'إشعار رسمي — سند لأمر متأخر', titleEn: 'Formal notice — overdue promissory note', bodyAr: 'إشعار رسمي: السند {number} بقيمة {outstanding} ر.س متأخر منذ {due}. عدم السداد يتيح للدائن التنفيذ عبر ناجز.', bodyEn: 'Formal notice: note {number} for SAR {outstanding} is overdue since {due}. Non-payment allows enforcement via Najiz.', deepLink: 'sinaaty://notes/{id}' },
  'enforcement.requested': { code: 'enforcement.requested', channels: ['push', 'sms'], titleAr: 'طلب تنفيذ السند عبر ناجز', titleEn: 'Enforcement requested via Najiz', bodyAr: 'الدائن طلب تنفيذ السند {number} بقيمة {claimed} ر.س. يمكنك السداد الآن لإيقاف الإجراء.', bodyEn: 'The creditor requested enforcement of note {number} for SAR {claimed}. Pay now to stop the process.', deepLink: 'sinaaty://notes/{id}' },
  'org.active': { code: 'org.active', channels: ['push', 'sms'], titleAr: 'تم اعتماد منشأتك 🎉', titleEn: 'Your organization is approved', bodyAr: 'أهلاً بك في صناعية — {org} أصبحت مفعّلة. أنشئ أول أمر إصلاح الآن.', bodyEn: 'Welcome to Sinaaty — {org} is now active. Create your first repair order.', deepLink: 'sinaaty://today' },
  'org.draft': { code: 'org.draft', channels: ['push', 'sms'], titleAr: 'طلب التوثيق يحتاج تعديلاً', titleEn: 'Verification needs changes', bodyAr: 'راجعنا وثائق {org}: {reason}. عدّل الوثائق وأعد الإرسال.', bodyEn: 'We reviewed {org}: {reason}. Fix the documents and resubmit.' },
  'org.suspended': { code: 'org.suspended', channels: ['push', 'sms'], titleAr: 'تم إيقاف المنشأة مؤقتاً', titleEn: 'Organization suspended', bodyAr: '{org} موقوفة مؤقتاً: {reason}. تواصل مع الدعم.', bodyEn: '{org} is suspended: {reason}. Contact support.' },
};
export function render(t: Template, data: Record<string, unknown>, locale: 'ar' | 'en') {
  const str = (v: unknown): string => { if (v === undefined || v === null) return ''; if (typeof v === 'string') return v; if (typeof v === 'number' || typeof v === 'boolean' || typeof v === 'bigint') return String(v); return JSON.stringify(v); };
  const fill = (s: string) => s.replace(/\{(\w+)\}/g, (_, k: string) => str(data[k]));
  return { title: fill(locale === 'ar' ? t.titleAr : t.titleEn), body: fill(locale === 'ar' ? t.bodyAr : t.bodyEn), deepLink: t.deepLink ? fill(t.deepLink) : undefined };
}
